### ISSUE TITLE
External subtitles (TTML/DFXP, WebVTT)?

### ISSUE THREAD

**Issue by qchroman** [Orange-OpenSource/hasplayer.js#101]
Hello,

Is there a way to pass link to external subtitles for player to render during playback?

Thank you.

**Comment by qchroman** [comment]
Hello all,

Sorry, may be no one had an experience with it? I mean, in-stream TTML/DFXP works ok when you playback Smooth Streaming asset. But, I can't figure out whether player supports external subs. I see that there are parsers for types mentioned above, but whether those are for external or in-stream subs?

**Comment by qchroman** [comment]
Sorry to trouble you all, but, please, let me know if external subs are at all possible with hasplayer?

Thank you.

**Comment by nicosang** [comment]
Please, could you explain what are external subs? have you an example with a smooth streaming stream and external subs?

**Comment by qchroman** [comment]
When I say external subtitles I mean a file which is a formatted based on TTML/DFXP or WebVTT specs. For example [this file](http://player.kaltura.com/modules/KalturaSupport/tests/resources/FishTmmlFeatureTest.en.xml) contains TTML/DFXP subtitles in it. And I was wondering whether you can pass it as subtitles source to the player. So player would display subtitles defined in this file.

You can take any Smooth Streaming asset available out there for video stream - [this one](http://playready.directtaps.net/smoothstreaming/TTLSS720VC1/To_The_Limit_720.ism/Manifest) for example.

Thank you.

**Comment by nicosang** [comment]
Ok, maybe for webvtt subtitles, you can just add a text track to html5 video element. For TTML, it is unfortunately not possible now.

**Comment by qchroman** [comment]
Thank you very much. I will try that. I just saw parsers inside the hasplayer, thought that may be it supports external subitles on its own. I guess those are for in-stream subtitles only.
