### ISSUE TITLE
Do you plan to support Ads?

### ISSUE THREAD

**Issue by qchroman** [Orange-OpenSource/hasplayer.js#113]
Hello all,

Is there a plan to support Ads, or, may be those are already supported and I missed something? We plan to playback Smooth Streaming assets (DRM protected).

Thank you.

**Comment by qchroman** [comment]
Ok, I guess there is no support on the roadmap for now.

**Comment by bbert** [comment]
Hello,
Which ad-insertion format are you interested in?

**Comment by qchroman** [comment]
Hello,

vast/mast with Smooth Streaming assets.

**Comment by qchroman** [comment]
Hello all,

If this is not yet supported, may be player may be used with 3rd party libraries that do support it?

Thank you.

**Comment by bbert** [comment]
Hi,
We have done some work on ads insertion (mast/vast), but we are waiting for internal agreement for publishing it.
We will let you know, asap.

**Comment by qchroman** [comment]
Awesome news. Thank you very much!

**Comment by bbert** [comment]
Hi,
Please look at adsplayer.js project: https://github.com/Orange-OpenSource/adsplayer.js.
I will try also to setup a demo page this week.

**Comment by qchroman** [comment]
Hello,

thank you very much for your response!

**Comment by pancioue** [comment]
Hello,
Thanks for the project.I'v tried to integrate with hasplayer. But it doesn't work.
I'm not sure our format 'MAST' and 'VAST' are correct or not. Is there any sample about it?

could you provide the test URL for "adsUrl" 

Thank you very much

**Comment by bbert** [comment]
Hello,
Please have a look at adsplayer.js project (https://github.com/Orange-OpenSource/adsplayer.js), a new sample application has been added by a contributor, so that you can test.

**Comment by pancioue** [comment]
Thank you for your response,
I will take a try
