### ISSUE TITLE
Audioplayback failure

### ISSUE THREAD

**Issue by antonino-tocco** [Orange-OpenSource/hasplayer.js#117]
Hi, I have Microsoft Smooth Streaming with Playready DRM  manifest to reproduce.
The video playback work great, but the MediaPlayer object not recognize the audioTracks.
AudioTracks have this format on manifest :
<StreamIndex Type="audio" QualityLevels="1" Chunks="3289" Url="QualityLevels({bitrate})/Fragments(audio_ita={start time})" Name="audio_ita" Language="ita">
		<QualityLevel Index="0" Bitrate="64000" FourCC="AACH" SamplingRate="24000" Channels="2" BitsPerSample="16" PacketSize="4" AudioTag="255" CodecPrivateData="131056E598"/>.
The audioTrack can have language="aaa". Is this a problem?

**Comment by antonino-tocco** [comment]
I have an update. I was able to reproduce audio on content, but my ADV not reproduce audio.
The audiotrack of adv has this format on manifest `<StreamIndex Type="audio" QualityLevels="1" Chunks="8" Url="QualityLevels({bitrate})/Fragments(audio={start time})" Name="audio" Language="ita">
		<QualityLevel Index="0" Bitrate="64000" FourCC="AACH" SamplingRate="24000" Channels="2" BitsPerSample="16" PacketSize="4" AudioTag="255" CodecPrivateData="131056E598"/>`

**Comment by bbert** [comment]
Hi,

"AACH" tracks are disabled since there is still some issues with HE-AACv2 support and interoperability across browsers and devices.
You can try enabling AACH by modifiying MssParser.js.
