### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by antonino-tocco** [Orange-OpenSource/hasplayer.js#119]
Hi, I have implement a SS + PR player for Microsoft edge with hasplayer.js.
The player work great, but sometimes , for example at first run, it perform an infinite loading cicle.
After reload the page it works correctly.
Can you help me ?

**Comment by bbert** [comment]
Hi,
Can you try again with current development branch? We have corrected one issue with PlayReady when using CustomData.
