### ISSUE TITLE
Issue with SS + PR

### ISSUE THREAD

**Issue by StephanCop** [Orange-OpenSource/hasplayer.js#121]
Hi all,
I need your help to understand two issues I am facing with a test Web Player that includes hasplayer.js to support Smooth Streaming contents protected with PlayReady on MS Edge.
First Issue:
1.  If I try to play a protected content for the first time, we receive from License Server the license included in the attachment “first_license_server_response.txt”. In this case, content playback fails since player is not able to decrypt content and player remains in black screen

[first_license_server_response.txt](https://github.com/Orange-OpenSource/hasplayer.js/files/348401/first_license_server_response.txt)
1.  If we then retry (after few seconds) to play the same content, we receive from License Server the license included in the attachment “second_license_server_response.txt”. In this case, content playback works correctly

[second_license_server_response.txt](https://github.com/Orange-OpenSource/hasplayer.js/files/348402/second_license_server_response.txt)

Now, the difference from output at point 1 and point 2 is the Revocation included in the license (tag <RevInfo>) and of course the file size. I checked that Revocation List is updated as suggested by Microsoft. 
Do you have an idea on how to solve it ?

Second Issue:

• When I am able to start content playback, then player stops systematically after 19 seconds. If I then pause and play content, it restarts from 19 seconds and then it plays to the end 

Please help me
Thanks

**Comment by bbert** [comment]
Hi,
Same question as in issue #119, with which version have you tested? Have you tried with development branch?

**Comment by StephanCop** [comment]
Hi, now I've tried with development branch and Issue number 1 is solved. Thank you.
I'm still experiencing Issue number 2. If you can help me, what information do you need to debug issue ? I can send them in private

**Comment by StephanCop** [comment]
Hi all, could you please help me ? Thanks a lot in advance

**Comment by bbert** [comment]
Hi,
Indeed we had an issue on Edge and IE11, since "seeked" event may not be raised in some cases.
This was disrupting the behavior of the buffering process (BufferController).
I have pushed some correction on development branch.
Please update and test again.
