### ISSUE TITLE
No way to select default audio track

### ISSUE THREAD

**Issue by djsuprin** [Orange-OpenSource/hasplayer.js#123]
Hello!

I'm having an issue with playing Smooth Streaming content with multiple audio tracks. All of them are English tracks, just using different codecs. The problem is that the first two audio tracks can't be played in the browser due to the missing EAC3 and AC3 codecs.

Because the player's strategy is to pick the first audio track of the given language or otherwise, the first in the manifest, it fails to initialize audio buffer controller. This in turn leads to inability to select another track using selectTrack method due to the following two problems.

Problem 1.

The logic inside selectTrack method is correct in most cases but in my particular case it is not correct because it iterates all existing tracks and picks the first, which id OR language is equal to the corresponding property of the given track that we want to select. But it my case all the audio tracks are English, so the player always picks the same first unsupported one.

I think the correct way should be to iterate tracks twice:
- First will select the track only if both IDs AND languages are matched. It will work for all the cases when track is selected using the result of getTracks first:

```
var tracks = player.getTracks();
player.selectTrack(tracks[2]);
```
- If by some reason the track haven't yet been selected, then the second iteration will try to match IDs OR languages, like it does now.

Problem 2.

Even if selectTrack picks the correct track, it fails to switch to it because audio buffer controller is not initialized. The solution could be to attempt to re-initialize it.

I have created [a workaround](https://github.com/djsuprin/hasplayer.js/commit/ecf7e87a96eebd7718d6525eababf585da2b05a4). Instead of picking only one audio track in the first place I iterate all of them (or all of the specific language, if it is given) until audio buffer controller is initialized correctly. I have this change in my fork and if you'd like I can create a pull request.

However maybe I am doing something wrong, have the player misconfigured or something? Any advise or help will be highly appreciated.

Thank you!

Kind regards,
Vladimir

**Comment by bbert** [comment]
Hi,
The solution should consist in removing not supported tracks when parsing manifest.
This is not done for (E)AC3 tracks.
Is the codec specified in FourCC field in your case? Do you have a manifest example?

**Comment by djsuprin** [comment]
Hello,

FourCC field values of the unsupported tracks are "EC-3" and "AC-3".

Supported ones are "AACL" and "AACH". By the way, somehow the last audio track (using "AACH") is not parsed, so getTracks() function returns only 3 first tracks. I can open a separate issue if you want.

Please find the manifest attached to this message.

[manifest.xml.zip](https://github.com/Orange-OpenSource/hasplayer.js/files/437222/manifest.xml.zip)

Kind regards,
Vladimir

**Comment by bbert** [comment]
I have updated MssParser.js on development branch to filter unsupported codecs.
For MSS, we dot support for the time being only the following codecs (FourCC):
- AVC1 and H264 for video tracks
- AAC and AACL for audio tracks
- TTML and DFXP for text tracks

This should resolve the problem 2.
This should also resolve in your case the problem 1. But if I well understood, the solution would consist in not considering audio tracks if an audio track with same language and id/name has already been parsed. Is that right?
