### ISSUE TITLE
smoothstream / playready errors when changing bit rate

### ISSUE THREAD

**Issue by briastev** [Orange-OpenSource/hasplayer.js#125]
When playing a smooth stream source encrypted with playready the stream starts but fails after a short time with a number of 
HTTP400: BAD REQUEST - The request could not be processed by the server due to invalid syntax. (XHR): GET
error messages.

These seem to be just after the event listener for bit rate change has been triggered.

If I add the line
player.setAutoSwitchQuality(false);

Then the entire stream is played without error.

**Comment by bbert** [comment]
Hi,
This may seems that only the first bitrate is available.
When swithing to other bitrates then you get 400 errors.

**Comment by briastev** [comment]
This happens on all of the streams I have tried. 

The streams are playing Ok in silverlight on IE11

**Comment by bbert** [comment]
Can you provide a test stream.

**Comment by briastev** [comment]
Bertrand,

This trailer stream exhibits the issue

https://d17ksqmxo9shr2.cloudfront.net/FYGNBZ95/O8ULVRR4E1JJ/hd/smooth/O8ULVRR4E1JJ_encrypted.ism/manifest

Brian Stevens

**Comment by briastev** [comment]
Stream information sent in email

**Comment by bbert** [comment]
Please reopen if issue is still valid?
