### ISSUE TITLE
encryption support (Widevine) for HLS

### ISSUE THREAD

**Issue by dluetkewiesmann** [Orange-OpenSource/hasplayer.js#127]
Hi all,

does the hasplayer support **HLS** in combination with **Widevine** DRM?

In https://github.com/Orange-OpenSource/hasplayer.js/issues/30 @bbert mentioned that there was no support for HLS and DRM at all back then. Unfortunately I couldn't find anything in the release notes indicating that DRM is supported by now.

Many thanks.

**Comment by bbert** [comment]
No, DRM is not supported for HLS.
