### ISSUE TITLE
HLS stream isn't playing

### ISSUE THREAD

**Issue by shacharz** [Orange-OpenSource/hasplayer.js#13]
In http://orange-opensource.github.io/hasplayer.js/1.2.0_dev/dashif.html
I chose HLS, and one of the example streams, and it didn't work. 
Tried other streams as well.

**Comment by bbert** [comment]
These HLs streams were working on chrome, it may has been broken with one of the last chrome upgrade. We will check and try to find the reason.
However, it works on IE11.

**Comment by guypaskar** [comment]
Do you know on which version of chrome it used to work?

**Comment by JobaDiniz** [comment]
+1

**Comment by JobaDiniz** [comment]
`http://109.199.58.6/1VYGfdAEJA4P17OCqFutzqHBd8HJWD45THbY=/7961/index.m3u8` throws `manifest cannot be parse, type is unkown !` both in Chrome and IE11

**Comment by bbert** [comment]
On my side, this stream works fine, both in Chrome and IE11.
I get a video with a still image.
Have you checked the request response data when requesting the manifest?

**Comment by JobaDiniz** [comment]
Ok for http://orange-opensource.github.io/hasplayer.js/1.2.0_dev/dashif.html it works, but it doesn't for the latest release, which is http://orange-opensource.github.io/hasplayer.js/1.1.0/dashif.html

**Comment by bbert** [comment]
Yes, version 1.1.0 is quite old. Please use version 1.2.0_dev. This 1.2.0 version should be released by the end of june.

**Comment by JobaDiniz** [comment]
Oh... https://github.com/Orange-OpenSource/hasplayer.js/releases are quite confusing... there is a [1.2.0](https://github.com/Orange-OpenSource/hasplayer.js/releases/tag/v1.2.0) version there but its date is old than [1.1.0](https://github.com/Orange-OpenSource/hasplayer.js/releases/tag/v1.1.0).

Question is, which branch has 1.2.0_dev?

**Comment by bbert** [comment]
Oh I see from where comes the confusion.
Since hasplayer.js is initially a fork from dash.js project, the https://github.com/Orange-OpenSource/hasplayer.js/releases page details also the relases of the dash.js project. Then 1.2.0 is the 1.2.0 release of dash.js project.

Then, please use 'development' branch of hasplayer.js project, which corresponds the 1.2.0 version of hasplayer.js being in development.
This version will be released (merged into 'master' branch) and tagged as "1.2.0".

**Comment by shacharz** [comment]
I tried both in Chrome and IE11 (on Win8.1) and Chrome on OSX and it didn't work.
The stream you provide in the example have no CORS - 
http://orange-opensource.github.io/hasplayer.js/1.2.0_dev/player.html?url=http://iphone.envivio.tv/iphone/downLoads/ch6/index.m3u8

When I tried a stream of my own it just was stuck, showing black screen and pretty much killing my cpu.
http://orange-opensource.github.io/hasplayer.js/1.2.0_dev/player.html?url=https://cdnapisec.kaltura.com/p/1375472/sp/137547200/playManifest/entryId/0_945p1zm2/flavorIds/0_7gbto9wn,0_lotoheyk/format/applehttp/protocol/https/a.m3u8

**Comment by bbert** [comment]
There is an issue with Envivio test stream, which produces a MEDIA_ERR_DECODE error. Need some time to analyze this issue.

Concerning your test stream there is some bugs in hasplayer.js:
- to manage your playlists that has https absolute URI for variant streams and chunks 
- to manage SPS,PPS (codec information) that is not contained in the very first TS packets of the video PID. It was assumed we should find these NALUs in the first TS packet. This has to be improved/corrected.
I will let you know when we will find time to implement these corrections, but do not hesitate to contribute if you can.

**Comment by bbert** [comment]
Corrected, see PR #20 (https://github.com/Orange-OpenSource/hasplayer.js/pull/20)
