### ISSUE TITLE
issue playing some live/dynamic dash contents

### ISSUE THREAD

**Issue by mpo22** [Orange-OpenSource/hasplayer.js#133]
The player is not able to play some live streams:
It fetchs segments but does not render video.

the following stream is correctly rendered in the dash.js player:
http://24x7dash-i.akamaihd.net/dash/live/900080/dash-demo/dash.mpd

hasplayer version
1.5.0_30d428b
2016-9-8_11:8:41  

plateform
windows+firefox

[hasplayerjs-live-issue-jsconsole.txt](https://github.com/Orange-OpenSource/hasplayer.js/files/508549/hasplayerjs-live-issue-jsconsole.txt)

**Comment by bbert** [comment]
Indeed, there are some issues for playing DASH live streams with hasplayer.js.
I recommend you using dash.js if your intention is to play only DASH streams.
