### ISSUE TITLE
Playback problem

### ISSUE THREAD

**Issue by tbrixi** [Orange-OpenSource/hasplayer.js#134]
playback not work on VOD SmoothStream with FragmentTime != 0,
stream with FragmentTime = 0 is OK,
tested on ver 1.6.0,

VOD SmoothStream manifest:
![capture](https://cloud.githubusercontent.com/assets/944480/19850693/187041b8-9f5a-11e6-8a0b-17a9f080b685.JPG)

**Comment by tbrixi** [comment]
on version 1.2.6 and 1.2.7 is playback OK,
on 1.3.0 and newer playback FAIL

**Comment by bbert** [comment]
Hi,
Can you provide a test stream?

**Comment by tbrixi** [comment]
Test Stream is valid only for a few hours, then starting re-encoding to FragmentTime=0.
ManifestUrl:
https://dc1-livemss-perform.secure.footprint.net/out/u/encr_5283330625_a1e4e97ed0694f94be3b4aedc8470b54.ism/Manifest

LaUrl: https://playready.entitlement.theplatform.eu/playready/rightsmanager.asmx?schema=1.0&auth=bw6jwmeaob7cm8Ju2CU2gZAM0KD0ACAW&releasePid=vi12i4hooIop&account=http%3a%2f%2faccess.auth.theplatform.com%2fdata%2fAccount%2f2689352799

**Comment by tbrixi** [comment]
I am not sure if VOD manifefest with "FragmentTime" > 0 is valid according to Smooth Streaming Protocol Specifications.

**Comment by tbrixi** [comment]
workaround: https://github.com/jozefchutka/hasplayer.js/commit/0b7f86664e456af24a4a2203237900755bd6eba7

**Comment by bbert** [comment]
Hi,
I have a made a PR (#139) inspired by what you proposed (keep original segments times from manifest only when constructing the requests URLs), and it seems to work fine now.
Let me know.

**Comment by krozalski** [comment]
@bbert  I belive your fixes in #139 resolved the issues on our side. We can close this I think.

Right @tbrixi?
