### ISSUE TITLE
Issue with DRM playback!

### ISSUE THREAD

**Issue by yeuser** [Orange-OpenSource/hasplayer.js#136]
Hi!

I tested this player with this url: http://hw10.asset.filimo.com/filimo-video/147999891042396829/1480056511/8713078020f05864db09a98e5c958c7f797c8705/3900-200k.mp4/chunk.m3u8?was=c2VydmVyX3RpbWU9MTEvMjMvMjAxNiA2OjQ4OjMxIEFNJmhhc2hfdmFsdWU9MXpsMDhmQzMva0luOXgrRUMrb0ZWQT09JnZhbGlkbWludXRlcz0xNDQwMCZpZD1leUp6ZVhOZmJtRnRaU0k2SW1acGJHbHRieUlzSW5ScGJXVWlPakUwTnprNE9ETTNNVEVzSW0xdmRtbGxYMmxrSWpvaU16STNNeUlzSW1GbVkyNGlPbTUxYkd3c0luZGhkR05vWDNSNWNHVWlPaUpsZEdNaUxDSnlibVIxYzJWeWFXUWlPaUl6TWpjek1UUTNPVGc0TXpjeE1UWTJOekkwTmlJc0luVnpaWEpmYVhBaU9pSTROQzR5TkRFdU5UWXVNVGN3SWl3aWQyUjFJam90TVN3aWJXOTJhV1ZmZFdsa0lqb2lNMlZzVjNraUxDSjFjMlZ5YVdRaU9qQXNJbVJsZG1salpYUjVjR1VpT2lKemFYUmxJaXdpYkhRaU9pSjJhU0o5

This is a true HLS format with adaptive bitrate and AES encryption.

There is a problem with sample load page, (http://orange-opensource.github.io/hasplayer.js/1.6.0/samples/Dash-IF/index.html) as it cannot load the given url correctly!

Also, when I ran the code myself by giving the url directly to the js instance of player, it seems the player is unable to parse the manifest:

hasplayer.js:4429 [10:44:44.756][Error] Code: MANIFEST_ERR_PARSE, Message: Failed to parse manifest, Data: {
	"url": "http://hw10.asset.filimo.com/filimo-video/147999891042396829/1480056511/871…xDSjFjMlZ5YVdRaU9qQXNJbVJsZG1salpYUjVjR1VpT2lKemFYUmxJaXdpYkhRaU9pSjJhU0o5"
}

**Comment by bbert** [comment]
Hi,
Your m3u8 manifest is not a variant streams playlist.
hlsplayer.js is an http **adaptive** streaming client, then aims to work with manifests describing different stream qualities/bitrates.
