### ISSUE TITLE
Issue while playing HLS with Dash-If player

### ISSUE THREAD

**Issue by viswanadhbysani** [Orange-OpenSource/hasplayer.js#138]
In chrome, while playing HLS "Back to the Mac" stream on [Dash-IF player](http://orange-opensource.github.io/hasplayer.js/1.7.0/samples/Dash-IF/index.html), it plays for sometime and later the page is presented with the following: 

**Aw, Snap!
Google Chrome ran out of memory while trying to display this web page.**

Chrome Version: 54.0.2840.99 m

Also if I play the same stream in Mozilla, it doesn't play. It keeps on showing the spinning wheel on the video player. And the corresponding log(mozillaLog.txt) is attached. It keeps downloading the same ts file again again but it doesn't play it. Please check the attached log file.

Mozilla Version: 50.0.2

[mozillaLog.txt](https://github.com/Orange-OpenSource/hasplayer.js/files/641420/mozillaLog.txt)

**Comment by bbert** [comment]
Hi,
HLS stack has been updated on development branch.
It should work better now, on chrome.
For Firefox, we still have some issues with some streams, especially "Back to the Mac".

**Comment by bbert** [comment]
Hi,
Found the issue for HLS on Firefox. See commit 05a5e81f53c7f6e22f2fd79a9fb844468a6f4aa7.

**Comment by viswanadhbysani** [comment]
Thank you very much for the response. Now after commit, I see that HLS related problems are fixed. I have tested using the link http://orange-opensource.github.io/hasplayer.js/development/samples/Dash-IF/index.html. 

However when I try playing the MSS streams 'VOD- SuperSpeedway' or 'Live - Big Buck Bunny' using Firefox, They keep on buffering and it never gets played. These MSS streams are playing fine in Chrome and also they are playing fine in firefox using the 1.7.0 link i.e. http://orange-opensource.github.io/hasplayer.js/1.7.0/samples/Dash-IF/index.html.

Could you please look into this problem as well?
Mozilla Firefox version: 50.1.0

Thank you!

[mozillaLog_mssProblems.txt](https://github.com/Orange-OpenSource/hasplayer.js/files/698481/mozillaLog_mssProblems.txt)

**Comment by bbert** [comment]
Yes, I confirm. I will let you know.

**Comment by bbert** [comment]
Sorry, I had been a little too fast in my previous commit. Now that should be ok.

**Comment by viswanadhbysani** [comment]
Thank you very much. Now they seem to play properly. Could you please let me know when is the next release (version: 1.8.0) planned?

**Comment by bbert** [comment]
It is planned for end of january.
Maybe not many more commits, but need some time to enrich functional tests and ensure no regression.
