### ISSUE TITLE
TypeError: MediaKeys.isTypeSupported is not a function

### ISSUE THREAD

**Issue by Avataren** [Orange-OpenSource/hasplayer.js#14]
I'm trying to play some playready encrypted smooth streaming content that requires customdata, but have not been able to succeed doing this. If I play content from the same server without protection it works fine (in Chrome), but not otherwise. 

I've tried both in http://orange-opensource.github.io/hasplayer.js/1.2.0_dev/dashif.html and locally.
I notice the console spits out this error "TypeError: MediaKeys.isTypeSupported is not a function", and it sounds like it might be related, but I'm not sure.

The complete console output can be seen here: http://pastebin.com/rm89kkWC

Any pointers on what I can do to make this work would be very welcome.

**Comment by bbert** [comment]
SS+PR decoding is not supported on chrome with current version.
PlayReady is supported only on IE11.
However, we are working on the support of PR on chrome, by "tranforming" PIFF+PR into CENC+Widevine within hasplayer.js, and assuming that you have a Widevine licenser that is able to provide the license able to decrypt the content.

**Comment by danny1lee** [comment]
Hi, I have the same problem.
I want play smooth streaming with drm(required custom data) on the IE11&Win 8.1.

They provided a test url, which does not play indeed:
http://orange-opensource.github.io/hasplayer.js/1.2.0_dev/dashif.html,

The log can be seen here:
http://pastebin.com/wGRiDHx6

Thank you for any help you can provide.

**Comment by bbert** [comment]
CustomData support is available.
Also a new version of EME support has been implemented in eme-refactor branch.
Please test with this version.
