### ISSUE TITLE
Example provided for DRM content is not playing Playready content

### ISSUE THREAD

**Issue by AswathyZ** [Orange-OpenSource/hasplayer.js#142]
Hi,

The example provided for playing DRM content is not actually playing a encrypted content.
http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest

Could you please provide a valid example.

```
<!doctype html>
<html>
    <head>
        <title>Hasplayer.js Rocks</title>
    </head>
    <body>
        <div>
            <video id="videoPlayer" controls="true"></video>
        </div>
        <script src="yourPathToHasplayer/hasplayer.js"></script>
        <script>
            (function(){
                var stream = {
                    url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest",
                    protData: {
                        com.microsoft.playready: {
                            laURL: "http://roap.purplecast.us/test/services/StandardPlayReadyAquireLicenseByContent.cfm?distrib=olps",
                            customData: "B2C99B73-CA41-4003-84A3AA16CE92B304"
                        }
                    }
                };
                var mediaPlayer = new MediaPlayer();
                mediaPlayer.init(document.querySelector("#videoPlayer"));
                mediaPlayer.load(stream);
            })();
        </script>
    </body>
</html>
```

Thanks!

**Comment by bbert** [comment]
Hi,
This example is indeed out of date, since the protection data syntax is wrong.
The syntax is the following:

     url: "<manifest_url>",
     protData: {
        com.microsoft.playready: {
            laURL: "<licenser_url>",
            cdmData: "<some_specific_CDM_data>"
        }
    }

However, the sample stream that is provided in this example is not protected... So it should play.

Here is en example of protected content with PlayReady (then works only on Edge and IE11):

     var stream = {
          url: "http://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism/Manifest"
    }

For this stream you don't need to provide licenser URL and cdmData

**Comment by AswathyZ** [comment]
Is there sample playready encrypted SMOOTH content which needs a license URL and token?

**Comment by bbert** [comment]
I have no public sample to provide
