### ISSUE TITLE
MEDIA_ERR_APPEND_SOURCEBUFFER while playing MPD

### ISSUE THREAD

**Issue by zasmarkany** [Orange-OpenSource/hasplayer.js#146]
Steps to reproduce:
open:
http://orange-opensource.github.io/hasplayer.js/development/samples/Dash-IF/index.html
use stream:
http://storage.googleapis.com/shaka-demo-assets/sintel/dash.mpd

Player plays first few seconds and then return an error:
"MEDIA_ERR_APPEND_SOURCEBUFFER"

**Comment by nicosang** [comment]
Hi Tomasz,
thanks for your contribution. Indeed, there was an issue in the VTTParser. You can test with the development branch.
