### ISSUE TITLE
Error while building the source

### ISSUE THREAD

**Issue by PraveenkumarDonga** [Orange-OpenSource/hasplayer.js#148]
Hi!
I first forked the repository into my account and then downloaded into my system.
Then I am trying to build it using the npm run build, but I am getting Errors as shown in the attached image.
Could any one help me with this.

Thanks,
Praveen.

![selection_006](https://cloud.githubusercontent.com/assets/8088246/23657247/2dc9b3e2-0363-11e7-87e8-24d39ffe4497.png)

**Comment by bbert** [comment]
Hi,
Have oyu installed the npm packages (npm install) as a first step?

**Comment by PraveenkumarDonga** [comment]
Hi!Bertrand Berthelot, 
I am getting this while running the npm install.
![selection_007](https://cloud.githubusercontent.com/assets/8088246/23693997/6de81ab4-03fd-11e7-92b9-91814857954d.png)

**Comment by bbert** [comment]
Hi,
You may have an issue with write access when creating symbolic links.
The issue is not related to node or npm or jsdoc package itself.
Please check internet for similar problems.
