### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'favicon.ico

### ISSUE THREAD

**Issue by PraveenkumarDonga** [Orange-OpenSource/hasplayer.js#149]
Hi!
I cloned the repository into my machine and moved that to my web server folder.
I didn't build it. Just I want to check How it is working.
So I created a html file as mentioned in the instructions and I am running the server.
When I am requesting  the .html file from the browser I am getting the below error.
Could any one help me with this?

The only change i have done is <script src="./hasplayer.js/app/js/streaming/MediaPlayer.js"></script> instead of <script src="Path to hasplayerjs/hasplayer.js> because I didn't find the hasplayer.js script in the hasplayer.js folder 

![selection_005](https://cloud.githubusercontent.com/assets/8088246/23657444/1d9c6f54-0364-11e7-92f9-0cae3d8b454b.png)

**Comment by bbert** [comment]
hasplayer.js is the build file containing all source code.
If you include only MediaPlayer.js, you will miss all the other source code files.

**Comment by PraveenkumarDonga** [comment]
Hi! bbert,
I didn't build it. just I want to check it as of now. 
So I am running it from http://127.0.0.1:8085/hasplayer.js/samples/Dash-IF/index.html
I am getting this Error. So Do you have any Idea about this?

ERROR:
Uncaught RangeError: Offset is outside the bounds of the DataView
    at DataView.getUint32 (<anonymous>)
    at Object.parseSIDX (BaseURLExtensions.js:54)
    at Object.parseSegments (BaseURLExtensions.js:125)
    at XMLHttpRequest.request.onload (BaseURLExtensions.js:503)

**Comment by PraveenkumarDonga** [comment]
I have followed the Reference Player steps.

**Comment by bbert** [comment]
Please provide the stream you tested, and the console logs

**Comment by PraveenkumarDonga** [comment]
Its working fine now.
Issue is with CORS setup in my HTTP server.
Everything is working fine now. I attached my server code.
[server.txt](https://github.com/Orange-OpenSource/hasplayer.js/files/854489/server.txt)
