### ISSUE TITLE
Cannot play ToTheLimit mss reference stream

### ISSUE THREAD

**Issue by smargaut** [Orange-OpenSource/hasplayer.js#153]
Hello, I am evaluating different javascript players, and the HAS player seems to be the most complete.
However, regarding smoothstreaming, I cannot play reference stream
http://playready.directtaps.net/smoothstreaming/TTLSS720VC1/To_The_Limit_720.ism/Manifest,
(tested with firefox and chrome) although I can play
http://playready.directtaps.net/smoothstreaming/SSWSS720H264/SuperSpeedway_720.ism/Manifest.
Did I miss something ?
Thank you for your help

**Comment by bbert** [comment]
In stream http://playready.directtaps.net/smoothstreaming/TTLSS720VC1/To_The_Limit_720.ism/Manifest, the video is encoded in WVC1 which is not supported by the hasplayer.js since it is not supported by all browsers.

**Comment by smargaut** [comment]
Indeed, I did miss that part, thank you very much for your answer
