### ISSUE TITLE
Stream not playing issue

### ISSUE THREAD

**Issue by amitsahu78** [Orange-OpenSource/hasplayer.js#160]
It seems the following smooth streaming url 
http://mahmadslvreg-s.akamaihd.net/ondemand/mahmad/perfect/EndtoEndWorld.ism/Manifest   does not play in http://orange-opensource.github.io/hasplayer.js/1.1.0/dashif.html in chrome browser.
But it can play in vlc player and also http://support.akamai.com/silverlight .
Can you please have a look why it can't play in hasplayer.js.
Let me know if you need any information.
Thanks and Regards,
Amit Sahu

**Comment by nicosang** [comment]
Hi,

the issue is due to video codec : WVC1. It's not supported.

Nicolas

**Comment by amitsahu78** [comment]
Hi Nicolas,
Thanks for the quick response. Just wanted to know, is there any plan to support this format in near future?
Thanks and Regards,
Amit Sahu

**Comment by nicosang** [comment]
hasplayer.js is based on MSE extensions normalized by W3C. In such cases, the decoding process is made by the browser. So, I can't answer...but I don't think so.

Nicolas

**Comment by bbert** [comment]
same as issue #37
