### ISSUE TITLE
Does HasPlayer support Failover?

### ISSUE THREAD

**Issue by porasl** [Orange-OpenSource/hasplayer.js#161]
I have several streams. I load the player with one stream and my expectation is player to ask for next active stream if current stream is interrupted or at least I expect player to throw an exception when stream is interrupted.  Does HasPlayer support FailOver?

**Comment by nicosang** [comment]
could you tell me which streaming protocol you use?

**Comment by porasl** [comment]
Smooth Stream

**Comment by bbert** [comment]
What do you mean "when the stream is interrupted"?
If the download of segments fails you should get an error (DOWNLOAD_ERR_CONTENT).

**Comment by porasl** [comment]
During live broadcast I plug out the data cable from the encoder (Camera). In this case what I see is a continues buffering player.

**Comment by bbert** [comment]
Maybe the player still receives data segments, but with "empty" data since you plugged out input data stream before encoder?
In that case, there is no way for the player to detect any error.

**Comment by porasl** [comment]
I find the reason: in v10 in line 3060 where loadNextFragment failed
          if (isDynamic){
                    // If live HLS, then check buffer since playlist should be updated
                   if (manifest.name === "M3U") {             //Check for player timeout
                        updateCheckBufferTimeout.call(this);
                    }
                } else {
                    // For VOD streams when stream is interrupted, signal end of stream
                    signalStreamComplete.call(this);
                }

There is no check for Live Smooth Stream. For Smooth Live 'isDynamic' is true, but this condition doesn't look for Smooth Stream. This condition is valid only for HLS. That is why player with Smooth Stream will just stay on buffering status.

**Comment by bbert** [comment]
Because in live there is no notion of end of stream.
So if I understand correctly, the last smooth segment the player received and processed does not contain the timestamps of the subsequents segments (in tfrf box). That is why the live segment timeline is interrupted. Do you confirm?
In that case, maybe we can imagine raising an error if tfrf is missing or empty.

**Comment by porasl** [comment]
Yes, it is exactly what I am looking for.

**Comment by bbert** [comment]
Addressed in PR #174
