### ISSUE TITLE
Dash+Playready : MEDIA_KEYSYSERR_ACCESS_DENIED

### ISSUE THREAD

**Issue by aleian84** [Orange-OpenSource/hasplayer.js#165]
Hi All,
I'm trying to play and encrypted playready content with : 

http://orange-opensource.github.io/hasplayer.js/1.10.0/samples/Dash-IF/index.html

I put the url of the content, the licenser url and the cdmData (all is correct, I play it with other player) but when I push button "Load" below error is raised : 

![image](https://cloud.githubusercontent.com/assets/25437433/26237924/4aa300e8-3c77-11e7-8b00-800d1d7421eb.png)

I have tried with the following code too : 

![image](https://cloud.githubusercontent.com/assets/25437433/26238023/a3b6f608-3c77-11e7-9aae-be1874dca5d5.png)

But the same error is raised. 

What is wrong?

Thanks in advance,

Alessio

**Comment by bbert** [comment]
There is no PlayReady CDM on chrome, only a Widevine one.
If you want to play PlayReady protected contents on chrome (firefox, opera, ...), you need to have a Widevine licenser server that is able to provide the decryption key which was used to encrypt the content.
Then, to enable the player to setup a Widevine EME session, you will have to provide the Widevine pssh to the player (in the protectionData).

**Comment by aleian84** [comment]
Thank you @bbert all is clear now.

Alessio
