### ISSUE TITLE
Get list of video resolutions 

### ISSUE THREAD

**Issue by abodelot** [Orange-OpenSource/hasplayer.js#177]
Hi, 

How can I retrieve the list of available video resolutions from a manifest?

For example, I would like to extract the list of resolutions from the *Representation* elements of a Dash manifest:

```xml
<AdaptationSet mimeType="video/mp4">
      <Representation bandwidth="309205" codecs="avc1.42c01e" height="288" id="video.1" maxPlayoutRate="4" width="512">
        ...
      </Representation>
      <Representation bandwidth="582396" codecs="avc1.42c01e" height="360" id="video.2" width="640">
        ...
      </Representation>
      <Representation bandwidth="889817" codecs="avc1.4d401f" height="432" id="video.3" width="768">
        ...
      </Representation>
</AdaptationSet>
```

And I'd like to extract resolutions (`512x288`, `640x360`, `768x432`), with their quality ID as well.

DashJS expose this information with the following method:

```js
// return array of video tracks with width, height, bitrate, qualityIndex
player.getBitrateInfoListFor('video');
```

Does hasplayer have methods for this? `getVideoBitrates()` only returns the list of bitrates, and `getTracks` only works with subtitles and audio types.

Note: I've only talked about the Dash format in my example, but a cross-format solution would be greatly welcomed.

Best,

-- Alexandre

**Comment by bbert** [comment]
Hi,
There is no dedicated API function to get video resolutions but you can get them by using the DashMetricsExtensions object:

`mediaPlayer.getMetricsExt().getBitratesWithResolutionForType("video")`
