### ISSUE TITLE
MEDIA_KEYMESSERR_NO_SESSION

### ISSUE THREAD

**Issue by jtrujillot** [Orange-OpenSource/hasplayer.js#182]
Because the following error may be returning on createKeySession function:

{"type":"error","data":{"code":"MEDIA_KEYMESSERR_NO_SESSION","message":"Failed to create key session","data":{"reason":"Failed to generate key request","error":{"code":null,"message":"UnknownError","data":"Rejected with system code (2)"}}}}

on line:

**session.generateRequest**("cenc", initData).then(function() {
                self.notify(MediaPlayer.models.ProtectionModel.eventList.ENAME_KEY_SESSION_CREATED, sessionToken);
            }).catch(function(ex) {
                removeSession(sessionToken);
                self.notify(MediaPlayer.models.ProtectionModel.eventList.ENAME_KEY_SESSION_CREATED, null, {
                    reason: "Failed to generate key request",
                    error: new MediaPlayer.vo.Error(ex.code, ex.name, ex.message)
                });
            });

Version Hasplayer: 1.7

In others device run 100%, but in one not work.

Tnks,

**Comment by bbert** [comment]
Can you detail the testing conditions? Which terminal? Which browser? Which CDM/key system? Which kind of stream?
This error is either due to the initData (pssh) you provided (manifest or init segment) or to the CDM itself ("Rejected with system code (2)")

**Comment by jtrujillot** [comment]
Hi,

I have a Set Up Box with Operta TV Browser,  the kind of stream is DRM PlayReady Smooth Streaming, How can I know what content decryption module has the stb?

Tnks.

**Comment by bbert** [comment]
Please check for the console logs to see which key system is avalable.
One more thing, can you use last version of the player?

**Comment by jtrujillot** [comment]
In this device only work the 1.7 version :( . tnks, 
The Log:
![image](https://user-images.githubusercontent.com/22380364/28169714-de27eb60-67a8-11e7-9ec2-28c68353d90d.png)

**Comment by bbert** [comment]
Your logs are truncated. Please have a look at all logs, you should see what's going on. Logs are enough explicit.

**Comment by jtrujillot** [comment]
Hi,

The complete log:

[13:52:19.587][MediaPlayer] set config: {
	"video": {
		"BufferController.minBufferTimeForPlaying": 20,
		"BufferController.minBufferTime": 30,
		"BufferController.liveDelay": 30,
		"ABR.minQuality": 0,
		"ABR.maxQuality": -1,
		"Debug.level": -1,
		"ABR.minBandwidth": -1,
		"ABR.maxBandwidth": -1,
		"ABR.switchUpIncrementally": false,
		"ABR.switchUpRatioSafetyFactor": 1.5,
		"ABR.latencyInBandwidth": true,
		"ABR.switchLowerBufferRatio": 0.2,
		"ABR.switchLowerBufferTime": -1,
		"ABR.switchDownBufferRatio": 0.5,
		"ABR.switchDownBufferTime": -1,
		"ABR.switchUpBufferRatio": 0.75,
		"ABR.switchUpBufferTime": -1,
		"ManifestLoader.RetryAttempts": 5,
		"FragmentLoader.RetryAttempts": 5
	},
	"audio": {
		"BufferController.minBufferTimeForPlaying": 30,
		"BufferController.minBufferTime": 30,
		"BufferController.liveDelay": 30
	}
} 
app-3fb2686cb9.js:4435 [13:52:19.598][MediaPlayer] set config: {
	"video": {
		"ABR.keepBandwidthCondition": true
	},
	"audio": {
		"ABR.keepBandwidthCondition": true
	}
} 
app-3fb2686cb9.js:4432 [13:52:19.611]<video> setCurrentTime (0) 
app-3fb2686cb9.js:4432 [13:52:19.702][StreamController] load url: https://fng-vod-qp.akamaized.net/ss/vol2/s/FNG_CP/i88109i207444/2017-07-06-17-07-20/contentvideoi88109i207444/output_ss.ism/manifest 
app-3fb2686cb9.js:4435 [13:52:20.186][ManifestLoader] Redirect URL: https://fng-vod-qp.akamaized.net/ss/vol2/s/FNG_CP/i88109i207444/2017-07-06-17-07-20/contentvideoi88109i207444/output_ss.ism/manifest 
app-3fb2686cb9.js:4432 [13:52:20.205][MssParser] Doing parse. 
app-3fb2686cb9.js:4432 [13:52:20.447][MssParser] Parsing complete (xmlParser: 92ms, mss2dash: 148ms, total: 0.24s) 
app-3fb2686cb9.js:4432 [13:52:20.452][StreamController] Manifest updated 
app-3fb2686cb9.js:4432 [13:52:20.455][StreamController] composeStreams 
app-3fb2686cb9.js:4432 [13:52:20.471][StreamController] Create stream 
app-3fb2686cb9.js:4435 [13:52:20.496][Stream] Create MediaSource 
app-3fb2686cb9.js:4435 [13:52:20.498][Stream] Setup MediaSource 
app-3fb2686cb9.js:4435 [13:52:20.509][MediaPlayer] ManifestReady 
app-3fb2686cb9.js:4435 [13:52:20.513][MediaPlayer] video bitrates: [161000,482000,840000,1497000,2495000,3996000] 
app-3fb2686cb9.js:4432 [13:52:20.515][StreamController] Manifest has loaded. 
app-3fb2686cb9.js:4432 [13:52:20.638][Stream] <video> loadstart event 
app-3fb2686cb9.js:4435 [13:52:20.657][Stream] Initialize MediaSource 
app-3fb2686cb9.js:4435 [13:52:20.725][BufferController][video] Initialize 
app-3fb2686cb9.js:4435 [13:52:20.732][BufferController][video] Update data 
app-3fb2686cb9.js:4435 [13:52:20.735][BufferController][video] Data changed 
app-3fb2686cb9.js:4435 [13:52:20.742][AbrController][video] Check rules.... 
app-3fb2686cb9.js:4435 [13:52:20.747][DownloadRatioRule][video] Checking download ratio rule... (current = 0) 
app-3fb2686cb9.js:4435 [13:52:20.749][DownloadRatioRule][video] No valid requests made for this stream yet, bailing. 
app-3fb2686cb9.js:4432 [13:52:20.754][AbrController][video] Request quality: 0 
app-3fb2686cb9.js:4432 [13:52:20.757][AbrController][video] Set quality: 0 
app-3fb2686cb9.js:4435 [13:52:20.759][AbrController][video] Check rules.... 
app-3fb2686cb9.js:4435 [13:52:20.761][DownloadRatioRule][video] Checking download ratio rule... (current = 0) 
app-3fb2686cb9.js:4435 [13:52:20.763][DownloadRatioRule][video] No valid requests made for this stream yet, bailing. 
app-3fb2686cb9.js:4432 [13:52:20.764][AbrController][video] Request quality: 0 
app-3fb2686cb9.js:4432 [13:52:20.766][AbrController][video] Set quality: 0 
app-3fb2686cb9.js:4435 [13:52:20.781][BufferController][audio] Initialize 
app-3fb2686cb9.js:4435 [13:52:20.784][BufferController][audio] Update data 
app-3fb2686cb9.js:4435 [13:52:20.785][BufferController][audio] Data changed 
app-3fb2686cb9.js:4435 [13:52:20.787][AbrController][audio] Check rules.... 
app-3fb2686cb9.js:4435 [13:52:20.788][DownloadRatioRule][audio] Checking download ratio rule... (current = 0) 
app-3fb2686cb9.js:4435 [13:52:20.790][DownloadRatioRule][audio] No valid requests made for this stream yet, bailing. 
app-3fb2686cb9.js:4432 [13:52:20.791][AbrController][audio] Request quality: 0 
app-3fb2686cb9.js:4432 [13:52:20.793][AbrController][audio] Set quality: 0 
app-3fb2686cb9.js:4435 [13:52:20.794][AbrController][audio] Check rules.... 
app-3fb2686cb9.js:4435 [13:52:20.795][DownloadRatioRule][audio] Checking download ratio rule... (current = 0) 
app-3fb2686cb9.js:4435 [13:52:20.797][DownloadRatioRule][audio] No valid requests made for this stream yet, bailing. 
app-3fb2686cb9.js:4432 [13:52:20.798][AbrController][audio] Request quality: 0 
app-3fb2686cb9.js:4432 [13:52:20.799][AbrController][audio] Set quality: 0 
app-3fb2686cb9.js:4435 [13:52:20.824][BufferController][text] Initialize 
app-3fb2686cb9.js:4435 [13:52:20.829][BufferController][text] Update data 
app-3fb2686cb9.js:4435 [13:52:20.831][BufferController][text] Data changed 
app-3fb2686cb9.js:4435 [13:52:20.833][AbrController][text] Check rules.... 
app-3fb2686cb9.js:4435 [13:52:20.835][DownloadRatioRule][text] Checking download ratio rule... (current = 0) 
app-3fb2686cb9.js:4435 [13:52:20.837][DownloadRatioRule][text] No valid requests made for this stream yet, bailing. 
app-3fb2686cb9.js:4432 [13:52:20.838][AbrController][text] Request quality: 0 
app-3fb2686cb9.js:4432 [13:52:20.840][AbrController][text] Set quality: 0 
app-3fb2686cb9.js:4435 [13:52:20.841][AbrController][text] Check rules.... 
app-3fb2686cb9.js:4435 [13:52:20.842][DownloadRatioRule][text] Checking download ratio rule... (current = 0) 
app-3fb2686cb9.js:4435 [13:52:20.844][DownloadRatioRule][text] No valid requests made for this stream yet, bailing. 
app-3fb2686cb9.js:4432 [13:52:20.846][AbrController][text] Request quality: 0 
app-3fb2686cb9.js:4432 [13:52:20.847][AbrController][text] Set quality: 0 
app-3fb2686cb9.js:4435 [13:52:20.852][EventController] Added 0 inline events 
app-3fb2686cb9.js:4435 [13:52:20.854][DRM] Initialize ProtectionController (video/mp4;codecs="avc1.4D401E", audio/mp4;codecs="mp4a.40.2") 
app-3fb2686cb9.js:4435 [13:52:20.856][DRM] Get supported key systems from content protection 
app-3fb2686cb9.js:4435 [13:52:20.862][DRM] Select key system 
app-3fb2686cb9.js:4435 [13:52:20.868][DRM][PM_21Jan2015] requestMediaKeySystemAccess: com.microsoft.playready 
app-3fb2686cb9.js:21686 requestMediaKeySystemAccess() is deprecated on insecure origins in the specification. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.
app-3fb2686cb9.js:4435 [13:52:20.884][Stream] Initialize playback 
app-3fb2686cb9.js:4435 [13:52:20.886][Stream] Setting duration: 5480.517 
app-3fb2686cb9.js:4435 [13:52:20.889][Stream] Playback initialized 
app-3fb2686cb9.js:4435 [13:52:20.917][DashHandler][video] getCurrentTime =>  0 
app-3fb2686cb9.js:4432 [13:52:20.920][Stream] Start time = 0 
app-3fb2686cb9.js:4432 [13:52:20.921][Stream] Seek: 0 
app-3fb2686cb9.js:4435 [13:52:20.924][Stream] startBuffering at time 0 
app-3fb2686cb9.js:4432 [13:52:20.925][BufferController][video] SEEK: 0 
app-3fb2686cb9.js:4432 [13:52:20.930][BufferController][audio] SEEK: 0 
app-3fb2686cb9.js:4432 [13:52:20.935][BufferController][video] START 
app-3fb2686cb9.js:4432 [13:52:20.936][BufferController][video] startPlayback 
app-3fb2686cb9.js:4432 [13:52:20.938][BufferController][video] stalled = true 
app-3fb2686cb9.js:4432 [13:52:20.939]<video> setPlaybackRate(0) 
app-3fb2686cb9.js:4435 [13:52:20.941][BufferController][video] Check buffer... 
app-3fb2686cb9.js:4435 [13:52:20.944][BufferController][video] Working time = 0, Buffer level = 0.000 
app-3fb2686cb9.js:4432 [13:52:20.948]<video> setCurrentTime (0) 
app-3fb2686cb9.js:4432 [13:52:20.950]<video> pause() 
app-3fb2686cb9.js:4432 [13:52:20.953][BufferController][video] BUFFERING - 0 - 0 
app-3fb2686cb9.js:4435 [13:52:20.958][BufferController][video] time to end = 5480.517 
app-3fb2686cb9.js:4435 [13:52:20.961][BufferController][video] Start buffering process... 
app-3fb2686cb9.js:4435 [13:52:20.962][AbrController][video] Check rules.... 
app-3fb2686cb9.js:4435 [13:52:20.964][DownloadRatioRule][video] Checking download ratio rule... (current = 0) 
app-3fb2686cb9.js:4435 [13:52:20.966][DownloadRatioRule][video] No valid requests made for this stream yet, bailing. 
app-3fb2686cb9.js:4432 [13:52:20.968][InsufficientBufferRule][video] Checking buffer level ... (current = 0, buffer level = 0, buffering = true) 
app-3fb2686cb9.js:4432 [13:52:20.970][AbrController][video] Request quality: 0 
app-3fb2686cb9.js:4432 [13:52:20.971][AbrController][video] Set quality: 0 
app-3fb2686cb9.js:4435 [13:52:20.972][BufferController][video] currentDownloadQuality changed : 0 
app-3fb2686cb9.js:4435 [13:52:20.974][BufferController][video] Send RepresentationSwitch with quality = 0 
app-3fb2686cb9.js:4435 [13:52:20.978][MediaPlayer][video] send download_bitrate - b=161000 
app-3fb2686cb9.js:4432 [13:52:20.981][BufferController][audio] START 
app-3fb2686cb9.js:4432 [13:52:20.982][BufferController][audio] startPlayback 
app-3fb2686cb9.js:4432 [13:52:20.983][BufferController][audio] stalled = true 
app-3fb2686cb9.js:4432 [13:52:20.985]<video> setPlaybackRate(0) 
app-3fb2686cb9.js:4435 [13:52:20.986][BufferController][audio] Check buffer... 
app-3fb2686cb9.js:4435 [13:52:20.987][BufferController][audio] Working time = 0, Buffer level = 0.000 
app-3fb2686cb9.js:4432 [13:52:20.990][BufferController][audio] BUFFERING - 0 - 0 
app-3fb2686cb9.js:4435 [13:52:20.992][BufferController][audio] time to end = 5480.517 
app-3fb2686cb9.js:4435 [13:52:20.994][BufferController][audio] Start buffering process... 
app-3fb2686cb9.js:4435 [13:52:20.995][AbrController][audio] Check rules.... 
app-3fb2686cb9.js:4435 [13:52:20.997][DownloadRatioRule][audio] Checking download ratio rule... (current = 0) 
app-3fb2686cb9.js:4435 [13:52:20.998][DownloadRatioRule][audio] No valid requests made for this stream yet, bailing. 
app-3fb2686cb9.js:4432 [13:52:20.999][InsufficientBufferRule][audio] Checking buffer level ... (current = 0, buffer level = 0, buffering = true) 
app-3fb2686cb9.js:4432 [13:52:21.000][AbrController][audio] Request quality: 0 
app-3fb2686cb9.js:4432 [13:52:21.002][AbrController][audio] Set quality: 0 
app-3fb2686cb9.js:4435 [13:52:21.003][BufferController][audio] currentDownloadQuality changed : 0 
app-3fb2686cb9.js:4435 [13:52:21.004][BufferController][audio] Send RepresentationSwitch with quality = 0 
app-3fb2686cb9.js:4435 [13:52:21.006][MediaPlayer][audio] send download_bitrate - b=161000 
app-3fb2686cb9.js:4435 [13:52:21.036][DRM] Get supported key systems from content protection 
app-3fb2686cb9.js:4435 [13:52:21.081][DRM] Get supported key systems from content protection 
app-3fb2686cb9.js:4432 [13:52:21.095][BufferController][video] Load request  0 
app-3fb2686cb9.js:4432 [13:52:21.100][BufferController][audio] Load request  0 
app-3fb2686cb9.js:4435 [13:52:21.104][BufferController][video] Initialization loaded  0 
app-3fb2686cb9.js:4432 [13:52:21.106][BufferController][video] Buffer initialization segment  0 
app-3fb2686cb9.js:4435 [13:52:21.112][BufferController][audio] Initialization loaded  0 
app-3fb2686cb9.js:4432 [13:52:21.113][BufferController][audio] Buffer initialization segment  0 
app-3fb2686cb9.js:4435 [13:52:21.122][BufferController][video] Buffering segment 
app-3fb2686cb9.js:4435 [13:52:21.127][BufferController][audio] Buffering segment 
app-3fb2686cb9.js:4435 [13:52:21.144][DRM] KeySystem Access (com.microsoft.playready) Granted!  Selecting key system... 
app-3fb2686cb9.js:4435 [13:52:21.145][DRM][PM_21Jan2015] Select key system, create new MediaKeys 
app-3fb2686cb9.js:4432 [13:52:21.151][Stream] <video> durationchange event: NaN 
app-3fb2686cb9.js:4432 [13:52:21.153][Stream] <video> ratechange event: 0 
app-3fb2686cb9.js:4432 [13:52:21.155][Stream] <video> timeupdate event: 0 
app-3fb2686cb9.js:4435 [13:52:21.157][BufferController][video] Working time = 0, Buffer level = 0.000 
app-3fb2686cb9.js:4435 [13:52:21.164][BufferController][audio] Working time = 0, Buffer level = 0.000 
app-3fb2686cb9.js:4435 [13:52:21.167][BufferController][text] Working time = 0, Buffer level = 0.000 
app-3fb2686cb9.js:4432 [13:52:21.181][Stream] <video> pause event 
app-3fb2686cb9.js:4435 [13:52:21.243][DRM][PM_21Jan2015] 'encrypted' event 
app-3fb2686cb9.js:4435 [13:52:21.249][DRM][PM_21Jan2015] 'encrypted' event 
app-3fb2686cb9.js:4432 [13:52:21.252][Stream] <video> durationchange event: 5480.517 
app-3fb2686cb9.js:4432 [13:52:21.254][Stream] <video> loadedmetadata event 
app-3fb2686cb9.js:4435 [13:52:21.257][DRM] KeySystem selected => create key session 
app-3fb2686cb9.js:4435 [13:52:21.270][DRM] Create key session 
app-3fb2686cb9.js:4435 [13:52:21.276][DRM][PM_21Jan2015] Create key session, type = temporary 
app-3fb2686cb9.js:4435 [13:52:25.112][BufferController][video] Segment buffered 
app-3fb2686cb9.js:4432 [13:52:25.117][Stream] Check start time 
app-3fb2686cb9.js:4435 [13:52:25.119][BufferController][audio] Segment buffered 
app-3fb2686cb9.js:4432 [13:52:25.122][Stream] Check start time 
app-3fb2686cb9.js:4435 [13:52:25.128][BufferController][video] loadNextFragment for time: 0 
app-3fb2686cb9.js:4435 [13:52:25.130][DashHandler][video] Getting the request for time: 0 
app-3fb2686cb9.js:4435 [13:52:25.138][BufferController][audio] loadNextFragment for time: 0 
app-3fb2686cb9.js:4435 [13:52:25.140][DashHandler][audio] Getting the request for time: 0 
app-3fb2686cb9.js:4435 [13:52:25.174][DashHandler][video] getIndexForSegments for time  0 
app-3fb2686cb9.js:4435 [13:52:25.176][DashHandler][video] getIndexForSegments, idx =   0 
app-3fb2686cb9.js:4435 [13:52:25.181][DashHandler][video] Index for time 0 is 0 
app-3fb2686cb9.js:4435 [13:52:25.184][DashHandler][audio] getIndexForSegments for time  0 
app-3fb2686cb9.js:4435 [13:52:25.186][DashHandler][audio] getIndexForSegments, idx =   0 
app-3fb2686cb9.js:4435 [13:52:25.190][DashHandler][audio] Index for time 0 is 0 
app-3fb2686cb9.js:4432 [13:52:25.194][BufferController][video] Load request  https://fng-vod-qp.akamaized.net/ss/vol2/s/FNG_CP/i88109i207444/2017-07-06-…deoi88109i207444/output_ss.ism/QualityLevels(161000)/Fragments(video_eng=0) 
app-3fb2686cb9.js:4435 [13:52:25.208][FragmentLoader][video] Load: https://fng-vod-qp.akamaized.net/ss/vol2/s/FNG_CP/i88109i207444/2017-07-06-…deoi88109i207444/output_ss.ism/QualityLevels(161000)/Fragments(video_eng=0) 
app-3fb2686cb9.js:4432 [13:52:25.213][BufferController][audio] Load request  https://fng-vod-qp.akamaized.net/ss/vol2/s/FNG_CP/i88109i207444/2017-07-06-…ideoi88109i207444/output_ss.ism/QualityLevels(96000)/Fragments(audio_spa=0) 
app-3fb2686cb9.js:4435 [13:52:25.218][FragmentLoader][audio] Load: https://fng-vod-qp.akamaized.net/ss/vol2/s/FNG_CP/i88109i207444/2017-07-06-…ideoi88109i207444/output_ss.ism/QualityLevels(96000)/Fragments(audio_spa=0) 
app-3fb2686cb9.js:4426 [13:52:25.852][DRM] Failed to create key session _log @ app-3fb2686cb9.js:4426error @ app-3fb2686cb9.js:4532onKeySessionCreated @ app-3fb2686cb9.js:19793dijon.System.notify @ app-3fb2686cb9.js:27889notify @ app-3fb2686cb9.js:8460(anonymous function) @ app-3fb2686cb9.js:22054
vendor-0ceba4e9d3.js:24420 452 - Error en el reproductor: {"type":"error","data":{"code":"MEDIA_KEYMESSERR_NO_SESSION","message":"Failed to create key session","data":{"reason":"Failed to generate key request","error":{"code":null,"message":"UnknownError","data":"Rejected with system code (2)"}}}}(anonymous function) @ vendor-0ceba4e9d3.js:24420error @ app-3fb2686cb9.js:38394onErrorListener @ app-3fb2686cb9.js:39647dispatchEvent @ app-3fb2686cb9.js:4798sendError @ app-3fb2686cb9.js:4664onProtectionError @ app-3fb2686cb9.js:8925dijon.System.notify @ app-3fb2686cb9.js:27889notify @ app-3fb2686cb9.js:8460onKeySessionCreated @ app-3fb2686cb9.js:19794dijon.System.notify @ app-3fb2686cb9.js:27889notify @ app-3fb2686cb9.js:8460(anonymous function) @ app-3fb2686cb9.js:22054
app-3fb2686cb9.js:4432 [13:52:25.858][StreamController] Reset 
app-3fb2686cb9.js:4426 [13:52:25.881][Error] Code: MEDIA_KEYMESSERR_NO_SESSION, Message: Failed to create key session, Data: {
	"reason": "Failed to generate key request",
	"error": {
		"code": null,
		"message": "UnknownError",
		"data": "Rejected with system code (2)"
	}
} _log @ app-3fb2686cb9.js:4426error @ app-3fb2686cb9.js:4532sendError @ app-3fb2686cb9.js:4668onProtectionError @ app-3fb2686cb9.js:8925dijon.System.notify @ app-3fb2686cb9.js:27889notify @ app-3fb2686cb9.js:8460onKeySessionCreated @ app-3fb2686cb9.js:19794dijon.System.notify @ app-3fb2686cb9.js:27889notify @ app-3fb2686cb9.js:8460(anonymous function) @ app-3fb2686cb9.js:22054
app-3fb2686cb9.js:4435 [13:52:25.888][FragmentLoader][audio] Loaded: https://fng-vod-qp.akamaized.net/ss/vol2/s/FNG_CP/i88109i207444/2017-07-06-…ideoi88109i207444/output_ss.ism/QualityLevels(96000)/Fragments(audio_spa=0) (200, 666ms, 4ms) 
app-3fb2686cb9.js:4435 [13:52:25.896][FragmentLoader][video] Loaded: https://fng-vod-qp.akamaized.net/ss/vol2/s/FNG_CP/i88109i207444/2017-07-06-…deoi88109i207444/output_ss.ism/QualityLevels(161000)/Fragments(video_eng=0) (200, 688ms, 2ms) 
app-3fb2686cb9.js:4432 [13:52:26.012][Stream] Pause. 
app-3fb2686cb9.js:4432 [13:52:26.014]<video> pause() 
app-3fb2686cb9.js:4435 [13:52:26.033][DRM][PM_21Jan2015] Teardown 
app-3fb2686cb9.js:4432 [13:52:26.042][Stream] Reset 
app-3fb2686cb9.js:4435 [13:52:26.045][Stream] stopBuffering 
app-3fb2686cb9.js:4432 [13:52:26.048][BufferController][video] STOP 
app-3fb2686cb9.js:4432 [13:52:26.053][BufferController][audio] STOP 
app-3fb2686cb9.js:4432 [13:52:26.056][Stream] Pause. 
app-3fb2686cb9.js:4432 [13:52:26.059]<video> pause() 
app-3fb2686cb9.js:4435 [13:52:26.142][MediaPlayer] Player is stopped

**Comment by bbert** [comment]
Then you can notice that PlayReady CDM is used, but, as I already said, this CDM returns an error when pushing initData into it. You have to check with your CDM provider.
There is nothing more we can do.

**Comment by jtrujillot** [comment]
ok, I'm going to escalate this error, very thenks.
