### ISSUE TITLE
Is there anyway to detect slide (Script Events) in the HasPlayer?

### ISSUE THREAD

**Issue by porasl** [Orange-OpenSource/hasplayer.js#183]
Hi,

I am looking for a way to detect the slide (Script Events) in the Smooth Stream.  Something like ID3 tag in HLS.

Thanks,
Hamid Porasl

**Comment by bbert** [comment]
Hi,
Don't know about script events.
Do you have a manifest and use case example?

**Comment by porasl** [comment]
During live broadcasting I push several slides to the stream and when I WireShark the received stream I see it contains information (URL) of pushed slides, Please see attached screenshot
![image](https://user-images.githubusercontent.com/27744802/28192841-a004a630-67ed-11e7-98ae-0830192e95e3.png)
I need to detect the value of "smoothStreamoutput:URL" in the HasPlayer.js Or an listen to an event if it already implemented in HasPlayer.js

**Comment by bbert** [comment]
Who makes the POST request '/Session.asmx' ?
It seems to be something done outside the context of the content session streaming. So this can not handled by the player. It may be handled at application level.
