### ISSUE TITLE
hasplayer no longer works on Edge 

### ISSUE THREAD

**Issue by bherdeg-disney** [Orange-OpenSource/hasplayer.js#184]
The hasplayer.js is used on Microsoft's PlayReady test site: 

   http://test.playready.microsoft.com/Home/Player

Protected PlayReady content stopped playing on Edge and Firefox about 10 days ago (still works on Internet Explorer 11.1480.14393.0).  

Investigating this, I discovered hasplayer.js - which is very nice!  (Thank you for developing this player!)

I don't see this posted as an issue, and think it should be either confirmed, or refuted (as it's always possible that some firewall, etc. may be blocking the use of this player inside our company).

Thank you for your time.

Brian

**Comment by bbert** [comment]
Hi,
I have tested following PR sample on Edge and it works:
http://test.playready.microsoft.com/service/rightsmanager.asmx?PlayRight=1&UseSimpleNonPersistentLicense=1

**Comment by bherdeg-disney** [comment]
Thanks bbert,

It does not work for me on Windows 10, accessing Microsoft test site: 

http://test.playready.microsoft.com/Home/Player

With the following content and LAURL:

Content: http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/manifest(format=mpd-time-csf)

LAURL: http://test.playready.microsoft.com/service/rightsmanager.asmx?PlayRight=1&UseSimpleNonPersistentLicense=1

Brian

**Comment by bbert** [comment]
That works alos but it takes long time before starting playing. Maybe an issue with license acquisition.
By the way, the hasplayer version embedded in Microsoft's PlayReady test site is very old (1.2.7).

**Comment by bherdeg-disney** [comment]
Hmmm - I never see the License Request - just the pre-roll:

GET http://test.playready.microsoft.com/Home/Player
200 OK (text/html)

CONNECT http://ajax.aspnetcdn.com:443
200 Connection Established ()

GET http://test.playready.microsoft.com/css/site.css?v=xDS5eVvOuNvKti5Bl5bOhCqX31NojrwK5g-KcnQNGeM
200 OK (text/css)

GET http://test.playready.microsoft.com/images/microsoft-logo-full-color-reversed.png
200 OK (image/png)

GET http://test.playready.microsoft.com/silverlight/silverlight.js
200 OK (application/javascript)

CONNECT http://ajax.aspnetcdn.com:443
200 Connection Established ()

CONNECT http://ajax.aspnetcdn.com:443
200 Connection Established ()

GET http://test.playready.microsoft.com/js/site.min.js?v=4YtIaePNzexGu4QQcABZ3hmCTZ5PpZ6UoIpVvTVV2ww
200 OK (application/javascript)

GET http://test.playready.microsoft.com/js/has/hasplayer.js
200 OK (application/javascript)

GET http://test.playready.microsoft.com/js/has/testplayer.js
200 OK (application/javascript)

GET https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js
200 OK (application/x-javascript)

GET https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js
200 OK (application/x-javascript)

GET https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css
200 OK (text/css)

GET http://go.microsoft.com/fwlink/?LinkId=161376
302 Redirect to http://download.microsoft.com/download/5/1/6/5165823D-1D79-4871-8AC2-42DDDB94A5C2/PNGs/SLMedallion_ENU.png

GET http://download.microsoft.com/download/5/1/6/5165823D-1D79-4871-8AC2-42DDDB94A5C2/PNGs/SLMedallion_ENU.png
200 OK (application/octet-stream)

GET http://tv-has.orange-labs.fr/piwik/piwik.js
200 OK (application/x-javascript)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/manifest(format=mpd-time-csf)
200 OK (application/dash+xml)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(970010)/Fragments(video=i,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(128003)/Fragments(aac_UND_2_128=i,format=mpd-time-csf)
200 OK (audio/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(970010)/Fragments(video=0,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(128003)/Fragments(aac_UND_2_128=0,format=mpd-time-csf)
200 OK (audio/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(970010)/Fragments(video=20000000,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(128003)/Fragments(aac_UND_2_128=20053333,format=mpd-time-csf)
200 OK (audio/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(5820064)/Fragments(video=i,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(128003)/Fragments(aac_UND_2_128=40106666,format=mpd-time-csf)
200 OK (audio/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(128003)/Fragments(aac_UND_2_128=60160000,format=mpd-time-csf)
200 OK (audio/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(128003)/Fragments(aac_UND_2_128=80213333,format=mpd-time-csf)
200 OK (audio/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(128003)/Fragments(aac_UND_2_128=100266666,format=mpd-time-csf)
200 OK (audio/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(128003)/Fragments(aac_UND_2_128=120320000,format=mpd-time-csf)
200 OK (audio/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(128003)/Fragments(aac_UND_2_128=140373333,format=mpd-time-csf)
200 OK (audio/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(5820064)/Fragments(video=40000000,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(2181139)/Fragments(video=i,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(2181139)/Fragments(video=60000000,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(3294017)/Fragments(video=i,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(3294017)/Fragments(video=80000000,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(5820064)/Fragments(video=100000000,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(11724731)/Fragments(video=i,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(11724731)/Fragments(video=120000000,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(19538914)/Fragments(video=i,format=mpd-time-csf)
200 OK (video/mp4)

GET http://profficialsite.origin.mediaservices.windows.net/c51358ea-9a5e-4322-8951-897d640fdfd7/tearsofsteel_4k.ism/QualityLevels(19538914)/Fragments(video=140000000,format=mpd-time-csf)
200 OK (video/mp4)

**Comment by bbert** [comment]
If you do not see license request that means you may already have the license in your license store.
