### ISSUE TITLE
customData in ProtectionModel_21Jan2015 (no cdmData parameter in createKeySession)

### ISSUE THREAD

**Issue by jtrujillot** [Orange-OpenSource/hasplayer.js#185]
Hi,

I am using Hasplayer 1.7 and licenseRequestMessage dont have customData segment in Opera TV Browser in a STB, I am trying in IE11 and licenseRequestMessage have customData segment, I think it's because IE11 works with ProtectionModel_3Feb2014, but in a STB works with ProtectionModel_21Jan2015 and createKeySession Function do not have cdmData parameter.

Tnks,

**Comment by bbert** [comment]
If your OperaTV does not support ProtectionModel_3Feb2014 then that means it does not support ms-prefixed EME version which provides support for custom data.

**Comment by jtrujillot** [comment]
@bbert thanks for your response, I am going to talk with team about this restriction.
