### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by mohojojo** [Orange-OpenSource/hasplayer.js#187]
Is the player sends the cookies when the license request is made? The license server is authenticating by a cookie :/

**Comment by bbert** [comment]
You have to set the parameter 'withCredentials' to true in the input key system protectionData object (see README).

**Comment by mohojojo** [comment]
yes, thx, meanwhile i found it.
But i encountered into an other problem, the playready init method never run, so the protdata property value is always null, and the cdmData xml part is not added to my request. What else i am missing?

**Comment by bbert** [comment]
"the playready init method never run" what do you mean exactly?
Which browser and platform are you using?

**Comment by bbert** [comment]
Please reopen if issue is still valid?
