### ISSUE TITLE
PlayReady minimum security level

### ISSUE THREAD

**Issue by mohojojo** [Orange-OpenSource/hasplayer.js#188]
Hi!

Can i set the minimum security level for the playready license acquisition? I get an error from a license server, they said it is maybe happens because of the level is lower then its needed.

**Comment by bbert** [comment]
Hi,
AFAIK nothing can be done at EME level.
I would say this is a compatibility problem between your licenser and your CDM/terminal.

**Comment by mohojojo** [comment]
Hi,

As i see i should use security level 2000. Can you explain it a bit how is this works in IE11, Edge?
Is this based on how secure the player is?

**Comment by bbert** [comment]
I'm not an expert in DRM technologies.
The security is not handled by the player but by the CDM which is embedded in the platform and then used by the player through EME API.
