### ISSUE TITLE
CDN Hasplayer not available

### ISSUE THREAD

**Issue by k-y0u** [Orange-OpenSource/hasplayer.js#197]
Hi,

It seems that the following link is done (404):
http://orange-opensource.github.io/hasplayer.js/1.10.0/hasplayer.min.js

I don't know if you're in charge of that, but if you are, could you make me a feedback on it?

**Comment by bbert** [comment]
There is an issue with Github pages (gh-pages branch). I will let you know when it will be back.

**Comment by bbert** [comment]
It is back.

**Comment by k-y0u** [comment]
Thank you!
