### ISSUE TITLE
Edge livestream with DRM (playready): rewind to beginning of stream causes error.

### ISSUE THREAD

**Issue by emanuel-macoun** [Orange-OpenSource/hasplayer.js#200]
I'm experiencing peculiar problem: when I try to rewind to the beginning of live stream (less than 10s from the start), I'm getting this error:
`[Error] Code: MEDIA_ERR_APPEND_SOURCEBUFFER, Message: Failed to append data into audio source buffer, Data: {
	"code": 22,
	"message": "QuotaExceededError",
	"data": "QuotaExceededError"
} `
What's interesting is that if I rewind fast enough (before initial buffer is full), then everything works correctly.

Environment: Windows 10 64-bit, Microsoft Edge 41.16299.15.0, hasplayer.js v1.13.0

**Comment by bbert** [comment]
I dit not managed to reproduce.
In hasplayer, we do not maintain past content in the buffers to avoid QuotaExceedeError, so I do not understand why you get this error, except if you have very limited memory.
Can you provide full logs of the hasplayer.js?

**Comment by emanuel-macoun** [comment]
Hi, I wasn't able to reproduce this issue now, I don't know why.
Anyway, I believe I have enough memory. I'm running Win10 64-bit in VirtualBox with 4GB RAM.
If I'm able to reproduce, I'll post full log.
