### ISSUE TITLE
4K video support

### ISSUE THREAD

**Issue by daniel-dias** [Orange-OpenSource/hasplayer.js#22]
I'm trying to play the 4K stream from DashIF, and as you can see, the video starts with 720p and then it changes to 4K.

But in the HasPlayer, the stream is always as 720p, never changing to 4K.
Stream: http://dashif.org/reference/players/javascript/1.3.0/samples/dash-if-reference-player/

HasPlayer doesn't have 4K support? if not, do you know when will it have?
Thanks.

**Comment by bbert** [comment]
The problems may come from a bad support for sidx and then byte-range requests for segments, since the hasplayer.js tries to download the whole representation files.
This has to be corrected for the next version.

**Comment by calexandre** [comment]
Hello, I am also interested in leveraging 4K for the HasPlayer.
Could you point some clues of where should we start? in terms of source files ofc...

**Comment by daniel-dias** [comment]
I was able to force the bitrate that i want to play the video, setting the setAutoSwitchQuality() to false and the setQualityFor() for the video bigger than the default quality, for example: 1 or higher. 

No matter how much i increase the value, the maximum bitrate that i can reach is 1620p, but then after some seconds the console shows the message:
- " [FragmentLoader][video] Load onprogress: it's too long!!!!!! " 

Eventually the video stops playing, and after some time i get this error:
- SCRIPT14: Not enough storage is available to complete this operation
- File: hasplayer.js, Line: 15982, Column: 43

Can you point me some direction i should go to solve this?
Thanks.

**Comment by bbert** [comment]
As I told you, since the support for byte-range from sidx boxes is not correctly supported, the player does not request segments from the original file but the whole file.
That is why the player notices that the downloading is taking too long time.

@calexandre: if you use 4K contents that are prepared without sidx and byte-ranges, that should be ok.
If you really want 4K with DASH you can try with dash.js player.

**Comment by calexandre** [comment]
@bbert since this problem is related to sidx and byte-ranges (DASH), do you think i will be able to stream 4K using a SmoothStreaming container without problems?

**Comment by bbert** [comment]
Yes, I would say hasplayer.js is theoretically agnostic to coding. The main question is to know if the browser supports 4K decoding.

Then, 4K means more data, therefore more javascript processing to transform segments from smooth streaming format to MSE's ISO BMFF Byte Stream format, but on PCs that should have no relevant impact.
