### ISSUE TITLE
FourCC="AACH" does not work for smooth streaming.

### ISSUE THREAD

**Issue by PatrikCarlander** [Orange-OpenSource/hasplayer.js#247]
Codec AACH is not in the list of accepted coded. (SUPPORTED_CODECS)
But I can play if I add it in a custom branch.

Can you please update the list to also accept AACH?

**Comment by bbert** [comment]
On which browser did you tried?
We explicitely disabled AACH due to interoperability issues on some browsers and terminals/PCs.
We made the choice to disable AACH to avoid decoding issues on some configurations, but this can be reconsidered according to browser evolutions

**Comment by PatrikCarlander** [comment]
I have test streams with AACH with latest Chrome, Firefox, Edge and IE11 on Windows 10.
It works after I patch hasplayer
     SUPPORTED_CODECS = ["AAC", "AACL", "AVC1", "H264", "TTML", "DFXP", "AACH"],

**Comment by bbert** [comment]
The problem is that I also tested on my side some streams with AACH audio, and parsing by the browser video decoder of the MP4 initialisation segment failed.
Thus, I do not feel confident to enable AACH representations.
But you can still fork and modify on your side for your needs.

**Comment by PatrikCarlander** [comment]
Thanks
