### ISSUE TITLE
Playready + Dash?

### ISSUE THREAD

**Issue by michaelszutu** [Orange-OpenSource/hasplayer.js#249]
I'm trying to figure out how to pass my playready token I get?

var stream = {
                    url: mediaUrl,
                    protData: {
                        "com.microsoft.playready":{
                            laURL: "https://xxxxxxxxx/rightsmanager.asmx",
                            customData: opts.token <-??? this correct?
                        }
                    }
                };
Also, my understanding is that chrome can't play encrypted playready streams. Can I test this in edge?

**Comment by bbert** [comment]
Please use cdmData property (not customData) as indicated in the README.
```
var stream = {
    url: mediaUrl,
    protData: {
        "com.microsoft.playready":{
            laURL: "https://xxxxxxxxx/rightsmanager.asmx",
            cdmData: opts.token
        }
    }
};
```

Please be advised that this project will no longer evolve, you can preferably use https://github.com/Dash-Industry-Forum/dash.js
