### ISSUE TITLE
Support of PlayReady Server SDK v1.5

### ISSUE THREAD

**Issue by dantepregal** [Orange-OpenSource/hasplayer.js#250]
Hi

Do the player has support for using PlayReady Server SDK v. 1.5 ?

**Comment by jeffcunat** [comment]
Hi @dantepregal, 

It is not a matter of the player but rather a browser or OS compatibility point.
See  [microsoft playready compatibilitymatrix](https://docs.microsoft.com/en-us/playready/overview/product-versions#playready-compatibility-matrix)
