### ISSUE TITLE
Switch audio track not working

### ISSUE THREAD

**Issue by JobaDiniz** [Orange-OpenSource/hasplayer.js#26]
Tested here: http://orange-opensource.github.io/hasplayer.js/1.2.1_dev/dashif.html
Manifest: http://109.199.57.6/3kwuzuwibbfflwtzlisgsl6chlj6l74xgcrawv2slhi======/6641/stream0010.isml/Manifest

When selecting *eng* language, playback freezes.

**Comment by bbert** [comment]
Audio track switching has been improved in latest version.
