### ISSUE TITLE
cannot set licenseserver-URL

### ISSUE THREAD

**Issue by tLupus1978** [Orange-OpenSource/hasplayer.js#27]
An JS error occurs when I try to set the LAURL in Demo-Player (in Chrome, but also in IE & Firefox, Windows 7)
![2015-07-21_11h14_29](https://cloud.githubusercontent.com/assets/10669923/8797122/bc815346-2f99-11e5-81d1-e5b1101a1168.png)

Usecase: Trying playback of PlayReady encrypted SmoothStream on Google Chrome browser by using Widevine Proxy. but Proxy (LAURL)  cannot be set.

**Comment by bbert** [comment]
Corrected, see commit https://github.com/Orange-OpenSource/hasplayer.js/commit/6179de554401127a8be9d8f3380c3acd7d5b3267

**Comment by bbert** [comment]
Please use development branch's version (http://orange-opensource.github.io/hasplayer.js/1.2.1_dev/dashif.html) to check the correction.
