### ISSUE TITLE
EDGE Browser can't play SmothStreaming with Playready

### ISSUE THREAD

**Issue by danny1lee** [Orange-OpenSource/hasplayer.js#31]
I try this sample:
http://orange-opensource.github.io/hasplayer.js/1.2.1_dev/player.html?url=http://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism/Manifest

But it can't play.

The Edge browser is  version 20.10240.16384.0.
Do you have the same problem?
Thanks a lot!

**Comment by bbert** [comment]
Hi,
There was a side effect since Edge browser was detected as a chrome browser ('chome' string is present in the user agent...).
The problem is corrected now on development branch.
