### ISSUE TITLE
Chrome - PlayReady video error - PSSH Key

### ISSUE THREAD

**Issue by swontroba** [Orange-OpenSource/hasplayer.js#32]
Similar to https://github.com/Orange-OpenSource/hasplayer.js/issues/31 in Chrome with a Play Ready Video file, I get the following error: [BufferController][text] Problem during init segment generation "Cannot read property 'pssh' of undefined" _log @ hasplayer.js:6572

Is the player supposed to work with "normal" PlayReady files on Edge or Chrome?

**Comment by itaykinnrot** [comment]
you can't player playready on chrome - chrome includes only widevine CDM

**Comment by swontroba** [comment]
I am not so sure about that. I understood that the player will grab a
playready encoded piff stream and adapt it on the fly to dash cenc. So if
you place a widevine server url in the lic acquisition field it get's the
correct key to decode. Well so my theory and what I understood the player
is doing.
Am 09.08.2015 11:57 schrieb "iKinnrot" <notifications@github.com>:
