### ISSUE TITLE
Firefox - playback not working

### ISSUE THREAD

**Issue by kfeinUI** [Orange-OpenSource/hasplayer.js#35]
MSE isn't completely opened up yet to the public, but it is quite usable if you disable the white list. DASH.js, for example, works fine in my experience.

HLS playback with hasplayer.js, however, is not working (at least with my test stream). It gets stuck in the buffering stage.

Here's what I've been using:
http://cdn3.viblast.com/streams/hls/airshow/playlist.m3u8

Also remember to test against Mac Firefox as well as PC.

**Comment by bbert** [comment]
Yes, it seems we have an issue with live streams in general on firefox.
On my side, firefox is not a priority, but I will try to have a look on this issue in the next weeks.

**Comment by kfeinUI** [comment]
An FYI if you're not already aware is that the whitelist is Firefox is due to be removed soon in version 42. Targeted for early November.

**Comment by mhassman** [comment]
Just seconding the need for live streams on firefox. Thnx!

**Comment by mhassman** [comment]
Hi,  Any chance there has been time to look into this? Happy to assist testing if that's helpful.

**Comment by bbert** [comment]
Live streams are now supported in firefox
