### ISSUE TITLE
HLS playback stops

### ISSUE THREAD

**Issue by kfeinUI** [Orange-OpenSource/hasplayer.js#36]
Seems to happen across browsers. After playing for a while, playback stops and the console just shows repeated "loadNextFragment failed" messages. The network tab shows that m3u8 requests continue to be made, but it ceases making requests for the ts fragments.

My test stream:
http://cdn3.viblast.com/streams/hls/airshow/playlist.m3u8

**Comment by bbert** [comment]
I've tried your test stream, and I do not notice any problem. It does not stop. Maybe it was a encoder/server issue.

**Comment by kfeinUI** [comment]
My office network is pretty crappy. Might be suggestive of an issue with how it copes with a less than optimal connection.

**Comment by ciAnd7** [comment]
Hi,

May be it is off topic, but it seems hasplayer doesn't correctly play streams with high bitrate and/or profile. You could test, for example, stream 975k/stream.m3u8 from provided resource (854x480, 900k, High@L3.0). 

Is there any workarounds to use hasplayer with high bitrate/profile streams?

**Comment by bbert** [comment]
Hi,
I would it depens of the browser.
But in chrome on PC desktop, I can play all the profiles of your test stream.

**Comment by ciAnd7** [comment]
Hm. This is what I see for all bitrates on provided sample on Chrome for PC and Mac - video is scaled but played https://convaas.com/shared/hasplayer_1.png 
But sometimes some segments show correctly. Same on 1.2.0 version.

What could I do localize problem?

**Comment by kfeinUI** [comment]
I've observed the crunched video as well. Mac browsers definitely have
issues and need to be tested thoroughly. On PC, I would occasionally see
this. Would sometimes correct itself with time, but obviously not desirable.
