### ISSUE TITLE
MSS Playready content on Chrome

### ISSUE THREAD

**Issue by dsilhavy** [Orange-OpenSource/hasplayer.js#43]
Hi, 
we are trying to play the MSS Playready sample file in Google Chrome.Can you provide us the content-key of the file?

http://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism/Manifest

Edit: Thanks, we found a solution

**Comment by bbert** [comment]
Hi,

Sorry, but I have no idea of what is the content-key of this stream. It comes from Microsoft PlayReady test server.

**Comment by adrees** [comment]
Hi Daniel,
I'm not sure if you found this already, but I think the ContentKey is:
eNqVnXrElmo2NSsn7IXeEA==
Cheers
Adam

**Comment by swontroba** [comment]
Hi dsilhavy 
where you able to play the play ready stream in chrome?

**Comment by dsilhavy** [comment]
Hi @swontroba 
yes we managed to play the PlayReady stream in Chrome. We used the following Content Key derived from the Key ID and the Key Seed:
tCyjFy7k5pv1GEilnbnNEw==
 
Best regards 
Daniel

**Comment by swontroba** [comment]
Hi Daniel
That is interesting - I tried it with the same Key ID and the Key Seed but failed to include the widevine lic server and pssh info. 
The play ready part works fine without problems in edge and ie
I included it like the code below, but it did not work.
May be I also have something wrong with my pssh info... 
Can you share some information how you include the widevine server and pssh ?
Thanks Sven

function launchPlayer() {
    if (metricsAgent && metricsAgentActive) {
        metricsAgent.createSession();
    }
    startTime = new Date();
    appendText("attachSource");
    
    streamSource = "http://x3smstr.dmm.t-online.de/smooth01/test/HSS/test-HD.ism/MANIFEST"
    
    /*
    player.attachSource(streamSource);
    */
    _customData = "<lapb version='1'>xxx</lapb>"
    
    player.attachSource(streamSource,
    {
    "com.microsoft.playready": {
        "customData": _customData, 
        "laURL": "https://xxxx /LicenseAcquisition.asmx"
    },
    "com.widevine.alpha": {
        "laURL": "https://proxy xxxx /proxy",
        "pssh": "xxx KgJIRA=="
    }
    });

**Comment by ManishKapoor1** [comment]
Hello,

I am working on a solution wherein we are trying to decrypt dash content given KeyId and Key seed. Can you share the keyid and keyseed for above manifest file? If you have reference code to calculate content key, that would also help.

Thanks in advance
Manish
