### ISSUE TITLE
seek in hls doesn't work (and wrong aspect ratio)

### ISSUE THREAD

**Issue by arikgilad** [Orange-OpenSource/hasplayer.js#49]
start chrome with --disable-web-security (because bipbopall.m3u8 doesn't have CORS; make sure to close all chrome browsers before starting chrome with --disable-web-security)

check url:
http://orange-opensource.github.io/hasplayer.js/1.2.1/player.html?url=http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8

1. it will start playing the video (and video apsec ratio is wrong; image is distorted)
2. seek to any position
3. video will not seek and will show loop of errors

[12:40:24.331][BufferController][video] loadNextFragment failed 
hasplayer.js:7617 [12:40:26.333][BufferController][video] Check buffer... 
hasplayer.js:7617 [12:40:26.333]Working time is video time: 622.457171 
hasplayer.js:7617 [12:40:26.336][BufferController][video] Buffer level = 0 (time:622.457171) 
hasplayer.js:7617 [12:40:26.336][BufferController][video] time to end = 1178.542829 
hasplayer.js:7617 [12:40:26.338][AbrController][video] Check rules.... 
hasplayer.js:7617 [12:40:26.341][DownloadRatioRule][video] Checking download ratio rule... (current = 3) 
hasplayer.js:7617 [12:40:26.341][DownloadRatioRule][video] DL: 0.193s, Total: 0.491s => calculatedBandwidth: 45839837.06720978 
hasplayer.js:7617 [12:40:26.343][InsufficientBufferRule][video] Checking buffer level ... (current = 3, buffer level = 0) 
hasplayer.js:7617 [12:40:26.353][DownloadRatioRule][video] SwitchRequest(3, 1) 
hasplayer.js:7617 [12:40:26.353][AbrController][video] Request for quality 3, priority = 1 
hasplayer.js:7617 [12:40:26.356][AbrController][video] Request for quality 999, priority = 0.5 
hasplayer.js:7617 [12:40:26.356][AbrController][video] Set quality: 3 
hasplayer.js:7617 [12:40:26.358][AbrController][video] Quality   boundaries: [-1,-1] 
hasplayer.js:7617 [12:40:26.358][AbrController][video] Bandwidth boundaries: [-1,-1] 
hasplayer.js:7617 [12:40:26.363][AbrController][video] Set playback quality: 3 
hasplayer.js:7617 [12:40:26.366][BufferController][video] loadNextFragment for sequence number: 2 
hasplayer.js:7617 [12:40:26.366][DashHandler][video] Getting the next request => sn = 2 
hasplayer.js:7617 [12:40:26.371][BufferController][video] loadNextFragment failed

**Comment by bbert** [comment]
Hi,

Still some issues with this stream (http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8), especially since MPEG2-TS PMT is different (video and audio PID differ) across the variant streams.
