### ISSUE TITLE
hls not playing valid m3u8 playlists

### ISSUE THREAD

**Issue by arikgilad** [Orange-OpenSource/hasplayer.js#50]
The following m3u8 doesn't play. It shows: 'No streams to play.':
http://orange-opensource.github.io/hasplayer.js/1.2.1/player.html?url=http://playertest.longtailvideo.com/adaptive/oceans/oceans.m3u8

In addition, the following doesn't play:
http://orange-opensource.github.io/hasplayer.js/1.2.1/player.html?url=http://playertest.longtailvideo.com/adaptive/captions/playlist.m3u8

shows error:
[15:44:01.084][HlsParser] no stream in HLS manifest _log @ hasplayer.js:7605error @ hasplayer.js:7661processManifest @ hasplayer.js:17479internalParse @ hasplayer.js:17497customParse @ hasplayer.js:9791onload @ hasplayer.js:8524XMLHttpRequest.send (async)doLoad @ hasplayer.js:8563load @ hasplayer.js:8576load @ hasplayer.js:11248play @ hasplayer.js:5957doAutoPlay @ hasplayer.js:5965attachSource @ hasplayer.js:6191launchPlayer @ player.js:683onLoad @ player.js:703x.Callbacks.c @ player.js:1597x.Callbacks.p.fireWith @ player.js:1640x.extend.ready @ player.js:807q @ player.js:717
hasplayer.js:7605 [15:44:01.144][ManifestLoader] Manifest parsing error. _log @ hasplayer.js:7605error @ hasplayer.js:7661(anonymous function) @ hasplayer.js:8530_rejected @ hasplayer.js:1463(anonymous function) @ hasplayer.js:1486makePromise.when @ hasplayer.js:1372promise.promiseDispatch @ hasplayer.js:1275(anonymous function) @ hasplayer.js:1198onTick @ hasplayer.js:1031
hasplayer.js:7605 [15:44:01.145][StreamController] Manifest loading error. 

Note: the two playlists works well in: http://demo.jwplayer.com/stream-tester/

**Comment by bbert** [comment]
- http://playertest.longtailvideo.com/adaptive/captions/playlist.m3u8: not a manifest with variant streams, this mode is not supported

- http://playertest.longtailvideo.com/adaptive/oceans/oceans.m3u8: video codec is malformed in the manifest (please chekc the logs in the console, "Video Codec video/mp4;codecs="mp4a.40.2,avc1.66.30") is not supported.").  Please check RFC6381: 

"When the first element of a value is a code indicating a codec from the Advanced Video Coding specification, ... , the second element (referred to as 'avcoti' in the formal syntax) is the hexadecimal representation of the following three bytes in the (subset) sequence parameter set Network Abstraction Layer (NAL) unit."
