### ISSUE TITLE
Audio playback failure on live smooth stream

### ISSUE THREAD

**Issue by vpolizzi** [Orange-OpenSource/hasplayer.js#52]
Hi, 
 trying to playback a live smooth stream broadcast using Microsoft Expression Encoder the player (Version: 1.2.1_dev_2082efe - 1.7.2015_17:34:15) fails to play the AACL audio track with the following error

Audio Codec (audio/mp4;codecs="undefined") is not supported. 

Looking at the manifest we found that the audio track QualityLevel element has an empty FourCC attribute:
 QualityLevel PacketSize="4" BitsPerSample="16" SamplingRate="44100" Channels="2" AudioTag="255" FourCC="" CodecPrivateData="1210" Bitrate="64000" Index="0"

The stream is played correctly using a Silverlight player.

**Comment by bbert** [comment]
Hi,
This issue has been corrected on development branch.
