### ISSUE TITLE
subtitle - display and custom ?

### ISSUE THREAD

**Issue by tybu** [Orange-OpenSource/hasplayer.js#56]
hi all,
I have a manifest with some subtitle.
I'd like to display, at first, the subtitles and in a second time to change its colors (text color, background color).
I can't find some functions / help / docs about this...

thanks in advance for any response ;-)

**Comment by inbre001** [comment]
@tybu : A little late but ... maybe helpful for others. To enable subtitles you can call the enableSubtitles() methode in the loadeddata/loadedmetadata  

```javascript
var mediaUrl = 'http://...';
var video = $('videoElementSelector').get(0);
var context = new MediaPlayer.di.Context()
var player = new MediaPlayer(context);
//
player.attachSource(mediaUrl);

//
video.addEventListener('loadeddata', function() {
        player.enableSubtitles(true);  // enables subtitles 
});
```

**Comment by tybu** [comment]
thanks for this informations :)

**Comment by bbert** [comment]
For subtitles enabling/disabling there was an issue. I've modified the code (on development branch) so that you can also enable/disable before attachSource(), without waiting for 'loadeddata' event.
