### ISSUE TITLE
IE/Edge problem and fix in KeySystem_PlayReady

### ISSUE THREAD

**Issue by qchroman** [Orange-OpenSource/hasplayer.js#60]
Hello all,

Just tried testing the playback of PlayReady protected Smooth Streaming asset in IE and Edge and found that in Edge it doesn't play. The reason is the following line (at least for me on Windows 10, Edge 25.10586.0.0)

    bytes = new Uint16Array(message.buffer);

in *KeySystem_PlayReady* function. Changing it to

    bytes = new Uint16Array(navigator.userAgent.indexOf("Edge") >= 0 ? message : message.buffer);

Fixed the issue. The reason of the error is that in Edge the message is *ArrayBuffer* already, but in IE it's *Uint8Array*. Just thought I'd share.

**Comment by bbert** [comment]
Hello,

This issue was already corrected on development branch, see commit https://github.com/Orange-OpenSource/hasplayer.js/commit/70679e3bd7be3f1257ba9d1ad99fcc4232c4ab03

**Comment by qchroman** [comment]
Hello,

Oh, ok, great. Thank you :)
