### ISSUE TITLE
MS Edge + PlayReady   CDM data (customdata)  missing / not passed on

### ISSUE THREAD

**Issue by inbre001** [Orange-OpenSource/hasplayer.js#68]
I am testing with MS Edge Browser against a PlayReady Licenser which requires to be pass some  CustomData to aquire a valid License.

I was hopefull and tried this
```bash
var protdata = {
                'com.microsoft.playready': {
                    customData: 'very very usefull business data'
                }
};
```
Unfortunelty this did not seem to change the LicenseRequest. 

Looking at 
* https://msdn.microsoft.com/en-us/library/dn457361.aspx
* https://msdn.microsoft.com/en-us/library/dn468979.aspx
* and [CDM Spec. MS](http://download.microsoft.com/download/E/A/4/EA470677-6C3C-4AFE-8A86-A196ADFD0F78/Content%20Decryption%20Module%20Interface%20Specification.pdf)  

and comparing this with the createKeySession() function in ProtectionModel_21Jan2015
it seems that the cdmData is not passed into the createSession() Function.

Since the cdmData was already availabe as an (unused) 3rd argument i tried passing it into the createSession(type, initData, cdmData), but this also did not change the LicenseRequest.
- No Error or Warning either.

Currently i suspect that the cdmData is not constructed as it should be.

Any help on this matter would be greatly appreciated.

**Comment by bbert** [comment]
You should have written:

```bash
var protdata = {
                'com.microsoft.playready': {
                    cdmData: 'very very usefull business data'
                }
};
```

'cdmData' instead of 'customData'.

Other comment: if you are up to date on development branch, we do keep using ProtectionModel_3Feb2014 for Edge browser.

**Comment by inbre001** [comment]
Using the latest development branch causes an 'Out of stack space' Exception on my Test Machine.
I will try it on a different Machine tomorrow and see how it goes.

What i find curious is that Edge selects the 'wrong' ProtectionModel. I think i'll try forcing the 3Feb2015 and see what happens.

Thanks for the quick response.

**Comment by qchroman** [comment]
Hello,

To my knowledge the Edge uses newer version of EME (difference in creationSession method of MediaKeys object) and forcing ProtectionModel_3Feb2014 will result in license acquisition and playback fail. 

ProtectionModel_21Jan2015 needs to be used.

**Comment by bbert** [comment]
Hello,

Edge uses a newer version of EME but also keeps compatibilty with MS-prefixed EME version, which enables license persistency natively. That is why we made the choice to keep using this version for the time being.

**Comment by qchroman** [comment]
Thank you bbert. BTW, you have download for the latest version on this page (http://orange-opensource.github.io/hasplayer.js/) point to previous one.

**Comment by inbre001** [comment]
I updated/switched to the latest development branch.
Now the ProtectionModel_3Feb2015 is used as predicted. 
Since here the cdm data is passed into createSession() i was hopefull.

Unfortunelty i can now reliably recreate an 'Out of stack space' Error. 

Happens after the Manifest was downloaded. 
I will try to find out some more details about the stack space error and maybe open a ticket/issue for it.

Since i can'f verify if the branch switch actually fixed this issue i would like to leave it open till i can confirm.

**Comment by bbert** [comment]
Which version of Edge do you have?

@qchroman : thanks, I corrected the link

**Comment by inbre001** [comment]
Microsoft Edge 25.10586.0.0
Microsoft EdgeHTML 13.10586

**Comment by bbert** [comment]
@inbre001 : I have the same Edge version, and the player loads ProtectionModel_3Feb2014 on it.
You can have a look at ProtectionModel_21Jan2015's detect() function, in which we do return false if MS-prefixed API (window.MSMediaKeys) is available.

**Comment by inbre001** [comment]
I could replicate the Out of stack space error on
https://orange-opensource.github.io/hasplayer.js/1.2.6/dashif.html

by using our Test Manifest
http://skywebvod-s.akamaihd.net/ondemand/Test/de_at/movies/F05016436____000332001/F05016436____000332001.ism/Manifest

Result: 
![Out of stack space](https://i.imgur.com/QWNAAE1.png)

@bbert:  I assume that means the Manifest itself or the ManifestParser is the Problem.

**Comment by bbert** [comment]
I really do not understand because on the same webapp, with the same browser, the player loads the protection model 3Feb2014.

FYI, I cannot really test your stream becasue the license request fails since I am not identified.

**Comment by inbre001** [comment]
@bbert  : Sorry if i did not make myself clear. 
The Protection Model is correct now. After the Branch switch. 

Problem is now the Out of Stack Error which accures during/after the parsing of the above Manifest.
(s. Image above)

**Comment by bbert** [comment]
This code comes from PR #53 and I've never fell into this case.
Also I do not have the Out of stack space error.

**Comment by inbre001** [comment]
@bbert :  The parsing of this [Manifest](http://skywebvod-s.akamaihd.net/ondemand/Test/de_at/movies/F05016436____000332001/F05016436____000332001.ism/Manifest) works for you ? And passes the  
```javascript
String.fromCharCode.apply(null, fixedCharCodes) 
```
without the Out of stack space error? 
That would be quite strange, because I can replicate the Error on 2 Different Machines (new setups, fully updated) 

And doing a quick websearch it seems that this might even be an known issue that has todo with a limit to the array that can be passed to the apply() method.

**Comment by inbre001** [comment]
closing this becasue the inital Problem 'passing the cdmData' has been solved with the switch to the latest development branch.
