### ISSUE TITLE
seekable range for live smooth streaming

### ISSUE THREAD

**Issue by jozefchutka** [Orange-OpenSource/hasplayer.js#73]
Hi,
I am trying to make hasplayer seeking live stream on IE11 according to the DVR information from manifest ( http://2is7server1.rd.francetelecom.com/C4/C4-51_BBB.isml/Manifest ... DVRWindowLength="6000000000"). It seems I can read current time value via video.currentTime as well as using it to seek back and forth a couple of seconds (video.currentTime = video.currentTime + 10). However I am not able to find any apis I could use to find seekable range (start/end). Is there anything provided by MediaPlayer I can use? Thanks

**Comment by bbert** [comment]
Hi,
We are actually working on this topic, we keep you in touch when we will provide something.

**Comment by bbert** [comment]
see PR #88
