### ISSUE TITLE
HLS MANIFEST_ERR_PARSE

### ISSUE THREAD

**Issue by ropoman** [Orange-OpenSource/hasplayer.js#75]
Hi,

Could you please tell me what is wrong with my HLS? It was created by Adobe Media Server.

[14:05:03.884][HlsParser] Doing parse.  hasplayer.js:7146:21
[14:05:03.885][HlsParser] #EXTM3U
#EXT-X-MEDIA-SEQUENCE:220005
#EXT-X-ALLOW-CACHE:NO
#EXT-X-VERSION:2
#EXT-X-TARGETDURATION:8
#EXTINF:8,
../../../../hls-live/streams/livepkgr/events/_definst_/liveevent/trendRobert-liveNum220005.ts
#EXTINF:8,
../../../../hls-live/streams/livepkgr/events/_definst_/liveevent/trendRobert-liveNum220006.ts
#EXTINF:8,
../../../../hls-live/streams/livepkgr/events/_definst_/liveevent/trendRobert-liveNum220007.ts
#EXTINF:8,
../../../../hls-live/streams/livepkgr/events/_definst_/liveevent/trendRobert-liveNum220008.ts
#EXTINF:8,
../../../../hls-live/streams/livepkgr/events/_definst_/liveevent/trendRobert-liveNum220009.ts
#EXTINF:8,
../../../../hls-live/streams/livepkgr/events/_definst_/liveevent/trendRobert-liveNum220010.ts
[14:05:03.886][HlsParser] no stream in HLS manifest  hasplayer.js:7134:21
[14:05:03.890][ManifestLoader] Manifest parsing error  hasplayer.js:7134:21
ERROR: {"type":"error","data":{"code":"MANIFEST_ERR_PARSE","message":"Failed to parse manifest","data":{"url":"http://192.168.169.125/hls-live/livepkgr/_definst_/liveevent/trendRobert-live.m3u8"}}} dashif.js:28503:1
[14:05:03.892][StreamController] Reset  hasplayer.js:7142:21
[14:05:03.893][Error] Code: MANIFEST_ERR_PARSE, Message: Failed to parse manifest, Data: {
	"url": "http://192.168.169.125/hls-live/livepkgr/_definst_/liveevent/trendRobert-live.m3u8"

Thanks a lot,
Ropo

**Comment by bbert** [comment]
The player supports HLS with a main manifest file containing variant playlists, since it intends to support http adaptive streaming.
