### ISSUE TITLE
Issue with player 1.2.6 playready- win10 - edge - Liz Server URL and custom data

### ISSUE THREAD

**Issue by swontroba** [Orange-OpenSource/hasplayer.js#76]
Hi 
I have a problem with windows 10, Edge 25.1058... and hasplayer 1.2.6
When playing protected content it seems like the player does ignore the Liz Server defined manually. 
Somehow it take the "old" out of the manifest ProtectionHeader or content?
Additionally I have problems with the custom data. It seems like they are not submitted.
Is this a bug? Can someone confirm? Don't know if this is edge specific or hasplayer specific

Thanks

**Comment by inbre001** [comment]
@swontroba : How does your ProtectionData look like?

**Comment by swontroba** [comment]
Do you mean the protection data of the video file itself or the structure?
I have to check if the protected video file itself also reference to the
old server.  As the video was encoded / protected before we switched
playready servers I assume it has the same url as the protection header in
the manifest.
I did not have access to the video file. Hopefully I get an answer / the
ismc,. on monday.
Overwriting the file / protection header data worked in the older edge and
hasplayer 1.2.1.
The whole setup / environment with protected videos and "new" lic server
overwriting works fine with a silverlight player.
So I assume it might have to do something with the changes in the new edge
version on win10 and the 1.2.6 Version of the hasplayer.
Thanks
Am 22.01.2016 19:48 schrieb "Ingo Breuer" <notifications@github.com>:

**Comment by inbre001** [comment]
@swontroba : I meant the ProtectionData Object you supply to the attachSource( url, protData) Method.

**Comment by swontroba** [comment]
ok - actualy I do not do any extra programming / attachSource within the
test. I use the 1.2.6 download player version put in on my localhost server
and place the data into the fields of the provided player. So the method
works like it is implemented in the code provided.

The later webpage which is personalized/ skinned has the player embeded and
attaches the data similar to the structure which I mentioned at the bottom
in (#43) limited to the play ready part at the moment.

**Comment by inbre001** [comment]
@swontroba : Ok, that helps to know. 
My suggestion would be that  you take a look at
```javascript
MediaPlayer.dependencies.protection.KeySystem_PlayReady :: getLicenseServerURL()  
```

**Comment by swontroba** [comment]
@inbre001 Thank you for your help / hints where to look. 
I will test and report, when I have access to the win10 test PC / setup

**Comment by swontroba** [comment]
@inbre001 I was debugging a little. 
It seem like your mentioned in #77 its not defined. 
There are some changes in the dashif.js file in the initPlayer() playready was changed completely to widevine chrome.
Just changing it back did not work - still have some problems. 
Have to check this with an other Developer...

**Comment by bbert** [comment]
Hi,
Indeed, the sample application was taking the widevine protection data when attaching source.
I updated the (Dash-IF) sample on development and master branches to enable selecting and setting the protection data according to protection scheme.

**Comment by swontroba** [comment]
ok - thank you
