### ISSUE TITLE
hasplayer not working in IE11

### ISSUE THREAD

**Issue by ShashiG88** [Orange-OpenSource/hasplayer.js#79]
Hi, I am using hasplayer.js for my html appliation for playing .ismv files and below is the example test file:
http://wams.edgesuite.net/media/MPTExpressionData02/BigBuckBunny_1080p24_IYUV_2ch.ism/manifest

        function setupVideo() {
            debugger;
            var context = new Custom.di.CustomContext();
            var player = new MediaPlayer(context);
            player.startup();
            player.attachView(document.querySelector('#videoplayer'));
            player.setAutoPlay(false);
            player.attachSource('http://wams.edgesuite.net/media/MPTExpressionData02/BigBuckBunny_1080p24_IYUV_2ch.ism/manifest', null, null);

        }

above is the js is working fine in chrome but in IE11 this is not working and error : unknown error occurred message is coming.

**Comment by bbert** [comment]
Hi,
Which version Windows? For Windows it will work only for Windows >= 8.1 (MSE/EME availability).
On my side, it worsk and chrome, IE11 and Edge.
