### ISSUE TITLE
Edge + PlayReady + ProtectionModel detect + customdata

### ISSUE THREAD

**Issue by AlePurga** [Orange-OpenSource/hasplayer.js#85]
Hi,

I downloaded the last dev version 1.2.7_dev and I tried to play a smooth streaming protected PlayReady.

I was able to reproduce it only after having force the player to use the 21Jan2015 ProtectionModel
(I commented `if(window.MSMediaKeys){
        return false;
    }` in detect function. Is this the right way to proceed?

Then I tried to send custom data to my licenser. I found a little typing error on main.js in dash-if sample ` $scope.cmdData = protData ? protData.cdmData : "";` corrected with `$scope.cdmData = protData ? protData.cdmData : "";` then when the player perform the license request I cannot see the custom data. I'm expecting a CustomData tag in the challenge. Do you have any idea on this?

**Comment by inbre001** [comment]
@AlePurga :  As far as i know you should use the ProtectionModel_3Feb2014 with Edge. Last time i checked the detecton should work. What was your reason for forcing the other ProtectionModel?  - And you might wanto to create a pull request to fix the typo.

**Comment by AlePurga** [comment]
@inbre001: if I use ProtectionModel_3Feb2014 the video doesn't start and I have the error "src not supporter", also the license request doesn't begin. I tried this solution because the dash.js player use the ProtectionModel_21Jan2015 for mpd so I made a simple test forcing the PM on hasplayer and all works fine. Now my biggest problem is how send custom data to the PlayReady Licenser. If I modify the request before to send it, the Licenser return an invalid challenge error.

**Comment by AlePurga** [comment]
I have a very strange behavior. I will try to explain it:

1. I have two playready crypted smooth streaming contents A and B. **A** is a microsoft content with a custom Licenser and **B** is self-produced content with the same Licenser of **A**.
2. I test them with ProtectionModel_3Feb2014 (PM14) and ProtectionModel_21Jan2015 (PM15).
3. The **content A** works only with PM15 and **content B** works on both PM

Now, you could say: "use the PM15 and all works fine", but seems that PM15 doesn't support the custom data and my solution runs only if the custom data are present in the license request. So I have to use the PM14 (as hasplayer recommends), but why doesn't the **content A**  work with PM14?

**Comment by bbert** [comment]
Hi,
When you say "the content A doesn't work with PM14", what kind of error do you have?

**Comment by AlePurga** [comment]
@bbert the error was "MEDIA_ERR_SRC_NOT_SUPPORTED"

**Comment by bbert** [comment]
Is it possible to get Microsoft content? To check what happens.

**Comment by AlePurga** [comment]
Sure, the Microsoft content is http://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism/Manifest, but the licenser in this manifest returns a license that doesn't allows playback on unknown output SD. I'm using a personal licenser to make it working.

**Comment by bbert** [comment]
This content works with PM 2014 (ms-prefixed EME's API), on IE11 and Edge.
If the problem is due to your output type, I can't help you. Maybe you can ask Microsoft for support.
Also, if it works with PM 2015, you can modify the source code for your version and explicitely use the PM 2015.
