### ISSUE TITLE
Can Hasplayer play .mp4?

### ISSUE THREAD

**Issue by AlePurga** [Orange-OpenSource/hasplayer.js#92]
Hi,
is there a way to play .mp4 files (or other progressive format) with Hasplayer?

My idea is to play both smooth streaming and mp4 formats using only hasplayer avoiding to use, for example, hasplayer for smooth streaming and native ones for mp4.

**Comment by bbert** [comment]
Hi,
hasplayer.js's functionning and API are valid and meaningful only for http adaptive streams.
You should preferably interacts directly with HTML5 video tag when you want to play mp4 files.
However you can share the same video tag for http adaptive streams (the one you attach to hasplayer.js via MediaPlayer.attachView()) and for mp4 files.
