### ISSUE TITLE
MSPlayready Play Infinite Buffering

### ISSUE THREAD

**Issue by antonino-tocco** [Orange-OpenSource/hasplayer.js#93]
Hi, I have try to play a SmoothStreaming content with PlayReady Drm , but the player stay in buffering without play nothing. Is all format of customData accepted by hasplayer?

**Comment by bbert** [comment]
Hi,
Did you get any error message? Please have a look in the console.

**Comment by antonino-tocco** [comment]
No, I haven't any error message in console. I have also add event listener for tipical events, such as loadstart, canplay, playing, pause, error. With Playready content with no encryption the player raise the events correctly, but with Playready content with encryption the player only raise event loading.

**Comment by bbert** [comment]
Which version do you test?
Is it possible to have access to the content? Or at least to provide all the console logs?

**Comment by antonino-tocco** [comment]
My version is last stable, 1.2.6. I don't have the permission to share the content.The only message in console logs is loading, beacuse I set this console log as callback for loadstart event.
This is how I set customData and playReady options:
var customData = "<Auth><cookie>e11897f57b83523767f39ca5c7c842ca85629a282814a6b3623dd8494be87965812e13f4afc07d6e88ad86139c63b191dfe933b0bb5346d96821e87193232db8</cookie><contentId>878045</contentId><type>EPISODE</type><channel>PCTV</channel><licenseType>streaming</licenseType></Auth>";
player.attachSource(url, {
            "com.microsoft.playready": {
                "customData": customData,
                "laURL": "licenserUrl"
            }
        });

**Comment by antonino-tocco** [comment]
I think that the player don't require the license because I don't view the request in the network panel of developer tools

**Comment by antonino-tocco** [comment]
Hi, i have also test with Microsoft Playready Manifest Url for test : http://playready.directtaps.net/smoothstreaming/. I tested with only manifest url ( with encryption) and protectionData 
{
  "com.microsoft.playready" : {
                "laURL": "http://playready.directtaps.net/pr/svc/rightsmanager.asmx"
     }
}
In this case nothing happens, the manifest was dowloaded correctly, but no request for fragment is visible. There aren't any error on console

**Comment by antonino-tocco** [comment]
[Error] Code: MEDIA_KEYSYSERR_ACCESS_DENIED, Message: No KeySystem/CDM available, Data: {
	"keySystems": [
		{
			"schemeIdURI": "urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95",
			"systemString": "com.microsoft.playready"
		}
	]
} . 
I have enale debugLevel ALL and i find this error on Firefoc and Chrome.

**Comment by bbert** [comment]
Of course, no PlayReady CDM on Firefox and Chrome.

**Comment by antonino-tocco** [comment]
Ah ok, thanks for the support
