### ISSUE TITLE
not possible to play MSS + playready

### ISSUE THREAD

**Issue by sebastieng** [Orange-OpenSource/hasplayer.js#95]
Hello,

I try to play an MSS stream encrypted with playready (IE11 + windows 10). The stream can be played by other player but not by hasplayer. Do you know why?

I attach the logs
[hasPlayer.txt](https://github.com/Orange-OpenSource/hasplayer.js/files/219411/hasPlayer.txt)

Thank you

**Comment by bbert** [comment]
Hello,
Could you provide the manifest and the first video fragment file?

**Comment by sebastieng** [comment]
By debugging the code, I have found the issue. The streams contains a box senc (PIFF 1.3) but it is not supported by the player

**Comment by bbert** [comment]
Maybe something is not correctly supported by the player in your senc box. If you could provide a sample, we would be able to analyze the issue.

**Comment by sebastieng** [comment]
The box senc  is not supported at all. It is not the same box than SampleEncryptionBox described in PIFF 1.1

In mp4lib.js, you should add something like this: 
 boxTypeArray["senc"] = ...

**Comment by sebastieng** [comment]
I need a player with support of key rotation. Does this player supports key rotation?

To support key rotation, you must specified the key id in video/audio fragments.
Key id can be specified in senc box or SampleEncryptionBox.

To add key rotation in SampleEncryptionBox , "flags &0x1" must be true. But in this case,  I think that PiffSampleEncryptionBox.read function is not correct:
  - you read sample_count before iv_size . Sample_count should be read after iv_size
  - after line if(this.flags &1), you don't read keyid and isencrypted flag

**Comment by eiximenis** [comment]
Hi @sebastieng 
Some time ago i did a minor update to hasplayer adding the "senc" box to mp4lib

I can get the commit(s) performed and integrate to the current development branch of has and perform a pull request if needed, but i would need a manifest to test the code, just to see if it solves your problem (my fix solved my own problem but was not intended to be a "universal" solution).
