### ISSUE TITLE
Edge Playback of html5 video with DRM (playready) does not work consistently

### ISSUE THREAD

**Issue by inbre001** [Orange-OpenSource/hasplayer.js#97]
Me and my collegues found a peculiar Problem with the playback of some PlayReady encryped streams.

It seems that on 3 of our Machines for testing the playback does not  work consistently. 
When it doesn't work only a BlackScreen is show and nothing happens. Even more preculiar is the fact that having the Edge Development Console open seems to inpact its frequency. With an open Dev Console  the Error seems to happens less often.

We tried finding a common denominator. And all we came up with until now seems to be that all 3 machines have the same graphics card (Intel HD Graphics 4600) - with latest drivers installed.

As of yet we assume it to be bug in the MS Edge Browser (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7240291/)
, but if you have any ideas or information about this issue i would greatly appreaciate your input. 

I will try to provide some access to the streams/media we use for testing, just to make sure if we did not miss anything. If you than would be so kind and take a look at them we would greatly appreciate your help. 

Thank you in advance for the help and 
the great work you did so for with this project.

**Comment by bbert** [comment]
Hi,
We can test on our side, you can provide me access to the streams.

**Comment by inbre001** [comment]
@bbert  I'll send you the Login Credentials via mail.

**Comment by bbert** [comment]
Please reopen if issue is still valid?
