### ISSUE TITLE
autoplay false

### ISSUE THREAD

**Issue by mdellanave** [Orange-OpenSource/hasplayer.js#98]
If I initialize the player with autoplay = false using this code

var context = new MediaPlayer.di.Context();
this.dashWrapper = new MediaPlayer(context);  
this.dashWrapper.startup();
this.dashWrapper.attachView(this.element);
this.dashWrapper.setAutoPlay(false);
this.dashWrapper.debug.setLevel(DASH_PLAYER_DEBUG_LEVEL);
 this.dashWrapper.attachSource(source.src);

when I click on the play button executing this code
this.element.play() (where element is the video tag)
the video remains all black

If I pass true to the setAutoPlay functions everythings works fine.

I think the problem is related to the live dash stream because if I use the http://dash.edgesuite.net/envivio/dashpr/clear/Manifest.mpd it seems every things works fine

Any suggestions?

**Comment by inbre001** [comment]
This from the result (the black video element) sounds a bit like  the Problem i had/have with  
https://github.com/Orange-OpenSource/hasplayer.js/issues/98 

With which Browser(Edge/Chrome) and Stream types (livestreams) did you observe this behaviour?
